'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {geoNaturalEarth1,geoPath,geoArea,geoCentroid} from 'd3-geo';
import {feature} from 'topojson-client';
import world from 'world-atlas/countries-110m.json';
import {makeNation,NationState,START_DATE} from '../lib/game-data';
import {getWorldProfile} from '../lib/world-database';
import {registerAdmin1Features} from '../lib/region-data';
import {historicalPolities,searchHistoricalPolities} from '../lib/historical-polities';
import {queryCliopatriaYear} from '../lib/cliopatria';
import {historicalRecords,searchHistoricalRecords} from '../lib/historical-records';
import {createWorldState,advanceWorld,advanceWorldWithData,issueCommand,issueCommandWithCatalyst,ensureNationSystems,syncPoliticalMap,applyEventEffects,interpretPlayerInstruction,hierarchyPath} from '../engine';
import type {WorldState} from '../engine';

const countries:any[]=(((feature(world as any,(world as any).objects.countries) as any).features??[]) as any[]);
const speeds=[1,2,5,10,20];
const tabs=['Overview','Politics','Economy','Diplomacy','Military','Intelligence','Advisor','Production','Technology','Population','Territory','News','Timeline','History','Commands'];
function mapFeatureId(f:any,index:number){const raw=f?.id; if(raw!==undefined&&raw!==null&&String(raw)!=='')return String(raw);const label=String(f?.properties?.name??'unit-'+index).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return 'unit-'+(label||index)}
type Preset={id:string;name:string;description:string;date:string;playerNation:string;state:WorldState};

function seedWorld(date=START_DATE,playerNation?:string):WorldState{
 const state=createWorldState(date);
 for(const f of countries){
  const id=mapFeatureId(f,countries.indexOf(f)), mapName=f.properties?.name??'Unknown', db=getWorldProfile(id,mapName), n=makeNation(id,db?.name??mapName);
  state.nations[id]={id:n.id,name:n.name,government:n.government,population:n.population,gdp:n.gdp,treasury:n.gdp*.15,debt:0,stability:n.stability,legitimacy:65,industrialCapacity:n.industry,civilianFactories:Math.max(5,Math.round(n.industry*.45)),militaryFactories:Math.max(2,Math.round(n.industry*.14)),dockyards:Math.max(1,Math.round(n.industry*.05)),manpower:n.population*n.manpowerRate,research:1,technology:['Agriculture','Basic Industry'],laws:[],relations:{},alliances:[],wars:[],ideology:n.ideology,politicalGoals:n.politicalGoals,resources:n.resources,strategicRegions:n.strategicRegions,majorCities:n.majorCities,historicalNotes:n.historicalNotes};
  const baseCentroid=geoCentroid(f as any) as [number,number]; const areaKm2=Math.max(1,geoArea(f as any)*6371*6371);
  state.mapEntities[id]={id,name:n.name,category:'country',controller:id,owner:id,areaKm2,population:n.population*1e6,mapSource:'bundled-world-atlas',centroid:baseCentroid,geometryKey:id,children:[],adjacency:[],development:n.industry,infrastructure:50,ratios:{childrenPerParent:0,populationShare:1,areaShare:1,urbanization:n.urbanization/100,density:n.population*1e6/areaKm2}};

  ensureNationSystems(state,state.nations[id]);
 }
 // Give every mapped nation a complete bilateral diplomacy matrix instead of leaving most panels empty.
 const ids=Object.keys(state.nations);
 for(const id of ids){
  const n=state.nations[id];
  for(const other of ids){if(other===id)continue; const a=Number(id)||0,b=Number(other)||0; n.relations[other]=Math.max(-100,Math.min(100,((a*31+b*17)%81)-40));}
  state.diplomacy[id].relations={...n.relations};
 }
 syncPoliticalMap(state); state.playerNation=playerNation??'840'; return state;
}
function pct(v:number){return Math.round(v*100)+'%'}
function identityColor(key:string){let h=0;for(const ch of key)h=(h*31+ch.charCodeAt(0))>>>0;return 'hsl('+h%360+' 38% 42%)'}
function formatBig(v:number){return v>=100?v.toFixed(0):v.toFixed(1)}
function safeNationName(state:WorldState,id:string){return state.nations[id]?.name??getWorldProfile(id,id)?.name??id}

export default function GameShell(){
 const [screen,setScreen]=useState<'launcher'|'game'>('launcher');
 const advancingRef=useRef(false);
 const [worldState,setWorldState]=useState<WorldState>(()=>seedWorld());
 const [selected,setSelected]=useState<NationState|null>(null),[selectedNationId,setSelectedNationId]=useState<string|null>(null),[selectedRegion,setSelectedRegion]=useState<string|null>(null);
 const [paused,setPaused]=useState(true),[speed,setSpeed]=useState(1),[tab,setTab]=useState('Overview');
 const [command,setCommand]=useState(''),[log,setLog]=useState<string[]>([]),[historyQuery,setHistoryQuery]=useState(''),[customDays,setCustomDays]=useState(30);
 const [lastInterpretation,setLastInterpretation]=useState<{objective:string;targets:string[];domains:string[];constraints:string[];interpretation:string;confidence:number}|null>(null);
 const [saves,setSaves]=useState<{name:string;date:string;state:WorldState}[]>([]);
 const [presetName,setPresetName]=useState(''),[presetDate,setPresetDate]=useState(START_DATE),[presetNation,setPresetNation]=useState('840');
 const [showMenu,setShowMenu]=useState(false),[changeNationOpen,setChangeNationOpen]=useState(false),[newsFilter,setNewsFilter]=useState<'all'|'major'|'military'|'diplomatic'|'economic'>('all'),[diplomacyTarget,setDiplomacyTarget]=useState<string>(''),[diplomacyDraft,setDiplomacyDraft]=useState(''),[diplomacyLog,setDiplomacyLog]=useState<{speaker:string;text:string}[]>([]),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[mapMode,setMapMode]=useState<'political'|'economy'|'military'|'resources'|'diplomacy'|'history'>('political'),[historicalFeatures,setHistoricalFeatures]=useState<any[]>([]),[historicalStatus,setHistoricalStatus]=useState<'idle'|'loading'|'ready'|'error'>('idle');
 const [admin1Features,setAdmin1Features]=useState<any[]>([]),[cityFeatures,setCityFeatures]=useState<any[]>([]),[geoStatus,setGeoStatus]=useState<'loading'|'ready'|'error'>('loading');
 const svgRef=useRef<SVGSVGElement|null>(null);
 const drag=useRef<{id:number;x:number;y:number;px:number;py:number}|null>(null);
 const pinch=useRef<{distance:number;zoom:number}|null>(null);
 const W=1200,H=650;
 const projection=useMemo(()=>geoNaturalEarth1().fitSize([W,H],{type:'FeatureCollection',features:countries} as any),[]);
 const path=useMemo(()=>geoPath(projection),[projection]);
 const liveNation=worldState.playerNation?worldState.nations[worldState.playerNation]:undefined;
 const viewedNationId=selectedNationId??worldState.playerNation??'840';
 const viewedLiveNation=worldState.nations[viewedNationId]??liveNation;
 const nation=viewedLiveNation?({...makeNation(viewedLiveNation.id,viewedLiveNation.name),...viewedLiveNation} as NationState):undefined;
 const activeEvents=worldState.events.filter(e=>!e.resolved&&(!e.expires||e.expires>=worldState.date));
 const visibleAdmin1=zoom>1.12?admin1Features:[];
 const visibleCities=zoom>2?cityFeatures:[];
 const warLines=useMemo(()=>{const lines:{a:string;b:string;ax:number;ay:number;bx:number;by:number}[]=[];for(const n of Object.values(worldState.nations)){for(const enemyId of n.wars){if(n.id>=enemyId)continue;const ai=countries.findIndex(f=>mapFeatureId(f,countries.indexOf(f))===n.id),bi=countries.findIndex(f=>mapFeatureId(f,countries.indexOf(f))===enemyId);if(ai<0||bi<0)continue;const ac=path.centroid(countries[ai]),bc=path.centroid(countries[bi]);if(Number.isFinite(ac[0])&&Number.isFinite(bc[0]))lines.push({a:n.id,b:enemyId,ax:ac[0],ay:ac[1],bx:bc[0],by:bc[1]});}}return lines;},[worldState.nations,path]);

 useEffect(()=>{try{const raw=localStorage.getItem('worldforge-saves');if(raw)setSaves(JSON.parse(raw));}catch{}},[]);
 useEffect(()=>{let alive=true;(async()=>{try{const base=new URL('./data/',window.location.href);const [a,cs]=await Promise.all([fetch(new URL('admin1.json',base)).then(r=>{if(!r.ok)throw new Error('admin1 '+r.status);return r.json()}),fetch(new URL('cities.json',base)).then(r=>{if(!r.ok)throw new Error('cities '+r.status);return r.json()})]);if(!alive)return;setAdmin1Features(a.features??[]);setCityFeatures(cs.features??[]);setWorldState(s=>{const next=structuredClone(s);registerAdmin1Features(next,a.features??[],cs.features??[]);return next});setGeoStatus('ready');}catch(err){console.error(err);if(alive)setGeoStatus('error')}})();return()=>{alive=false}},[]);
 useEffect(()=>{if(screen!=='game'||paused)return;const id=setInterval(()=>advanceAndInspect(speed),650);return()=>clearInterval(id)},[screen,paused,speed]);
 useEffect(()=>{if(screen==='game'){try{localStorage.setItem('worldforge-autosave',JSON.stringify(worldState));}catch{}}},[worldState,screen]);
 useEffect(()=>{let alive=true;if(screen!=='game'||mapMode!=='history'){setHistoricalFeatures([]);setHistoricalStatus('idle');return}setHistoricalStatus('loading');queryCliopatriaYear(Number(worldState.date.slice(0,4))).then(features=>{if(alive){setHistoricalFeatures(features);setHistoricalStatus('ready')}}).catch(err=>{console.error(err);if(alive)setHistoricalStatus('error')});return()=>{alive=false}},[screen,mapMode,worldState.date]);

 function enter(state:WorldState){const migrated=structuredClone(state);if(!Array.isArray(migrated.news))migrated.news=[];if(!migrated.scenario.branchId)migrated.scenario.branchId='legacy-'+migrated.seed+'-'+migrated.tick;if(migrated.scenario.lastAdvanceDays===undefined)migrated.scenario.lastAdvanceDays=0;if(!migrated.scenario.catalysts)migrated.scenario.catalysts={active:[],recent:[]};setWorldState(migrated);const p=migrated.playerNation??'840';setSelectedNationId(p);setSelected(makeNation(p,state.nations[p]?.name??'United States'));setScreen('game');setTab('Overview');setPaused(true);setPan({x:0,y:0});setZoom(1)}
 function newGame(){enter(seedWorld(presetDate,presetNation));setLog(['New simulation initialized.'])}
 function resume(){try{const raw=localStorage.getItem('worldforge-save');if(raw){enter(JSON.parse(raw));setLog(['Saved campaign resumed.']);return}}catch{} setLog(['No manual save found.']);}
 function quick(c:string){
 const s=structuredClone(worldState),player=s.playerNation??'';
 const parsed=issueCommand(s,c,player);
 let message=parsed.message,ok=parsed.ok;
 if(!ok){
  const ai=interpretPlayerInstruction(s,c,player);
  ok=ai.ok;message=ai.message;
  if(ok){s.scenario.historyLog.push('ai-order:'+s.tick+':'+c);setLastInterpretation(ai.intent?{...ai.intent,confidence:ai.confidence}:null);}
 }
 if(ok){
  const interpreted=lastInterpretation;
  s.scenario.divergence=Math.min(100,s.scenario.divergence+(c.toLowerCase().startsWith('war ')||c.toLowerCase().includes('invade')||c.toLowerCase().startsWith('ally ')?6:2));
  s.scenario.historyLog.push('command:'+s.tick+':'+c);
  issueCommandWithCatalyst(s,c,player);
 }
 setLog(x=>[(ok?'✓ ':'✕ ')+message,...x].slice(0,12));setWorldState(s);setShowMenu(true)
}
 async function advanceAndInspect(days:number){
  if(!Number.isFinite(days)||days<=0||advancingRef.current)return;
  advancingRef.current=true;
  const safeDays=Math.min(3650,Math.max(1,Math.round(days)));
  const before=worldState;
  const next=await advanceWorldWithData(before,safeDays);
  const fresh=next.news.filter(n=>!before.news.some(old=>old.id===n.id));
  if(fresh.some(n=>n.importance>=7))setPaused(true);
  if(fresh.length){const report=fresh.slice(0,3).map(n=>n.title+' · '+n.summary).join(' | ');setLog(x=>[report,...x].slice(0,12));}
  setWorldState(next);
  advancingRef.current=false;
 }
async function skipToMajor(){
 if(advancingRef.current)return;
 advancingRef.current=true;setPaused(true);
 let next=structuredClone(worldState),found=false;
 for(let i=0;i<104&&!found;i++){
  const before=next.news.map(n=>n.id);
  next=await advanceWorldWithData(next,7);
  const fresh=next.news.filter(n=>!before.includes(n.id));
  if(fresh.some(n=>n.importance>=6))found=true;
 }
 setWorldState(next);
 setLog(x=>[found?'Jumped to the next major development.':'No major development found in the next 2 years.',...x].slice(0,12));
 advancingRef.current=false;
}
function advanceBy(days:number){if(!Number.isFinite(days)||days<=0)return;setPaused(true);advanceAndInspect(days);setLog(x=>['Advanced '+Math.round(days)+' days.',...x].slice(0,12));}
 function selectCountry(id:string,name:string){
 const live=worldState.nations[id],profile=getWorldProfile(id,name),n=live?makeNation(id,profile?.name??live.name):makeNation(id,profile?.name??name);
 setSelectedNationId(id);setSelected(n);setSelectedRegion(null);setTab('Overview');setShowMenu(true);
}
 function save(){try{localStorage.setItem('worldforge-save',JSON.stringify(worldState));localStorage.setItem('worldforge-save-version','2.0');const entry={name:(worldState.nations[worldState.playerNation??'840']?.name??'Campaign')+' Campaign',date:worldState.date,state:worldState};const next=[entry,...saves.filter(s=>!(s.date===entry.date&&s.name===entry.name))].slice(0,8);localStorage.setItem('worldforge-saves',JSON.stringify(next));setSaves(next);setLog(x=>['Campaign saved on this device.',...x])}catch{setLog(x=>['Save failed.',...x])}}
 function createPreset(){const p:Preset={id:crypto.randomUUID(),name:presetName.trim()||'Custom Scenario',description:'Player-created Worldforge preset',date:presetDate,playerNation:presetNation,state:seedWorld(presetDate,presetNation)};try{const raw=localStorage.getItem('worldforge-presets');const list:Preset[]=raw?JSON.parse(raw):[];list.unshift(p);localStorage.setItem('worldforge-presets',JSON.stringify(list));setLog(['Preset created: '+p.name]);setPresetName('')}catch{}}
 function loadPresets():Preset[]{try{return JSON.parse(localStorage.getItem('worldforge-presets')||'[]')}catch{return[]}}
 const builtInPresets:Preset[]=[{id:'builtin-1936',name:'The World · 1936',description:'Baseline pre-war campaign',date:'1936-01-01',playerNation:'840',state:seedWorld('1936-01-01','840')},{id:'builtin-1939',name:'The World · 1939',description:'Late pre-war campaign',date:'1939-09-01',playerNation:'826',state:seedWorld('1939-09-01','826')},{id:'builtin-1941',name:'The World · 1941',description:'Global-war campaign',date:'1941-06-22',playerNation:'643',state:seedWorld('1941-06-22','643')},{id:'builtin-czech',name:'Czechoslovakia · 1941',description:'Alternate-history Central European campaign',date:'1941-11-13',playerNation:'203',state:seedWorld('1941-11-13','203')}];
 function startPreset(p:Preset){const s=structuredClone(p.state);s.scenario.presetId=p.id;s.scenario.presetDate=p.date;s.scenario.branchId='branch-'+s.seed+'-'+p.id;s.scenario.divergence=0;s.scenario.historyLog=[];s.scenario.historicalTrackers={};s.scenario.catalysts={active:[],recent:[]};enter(s)}
 function onWheel(e:React.WheelEvent){e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();const mx=(e.clientX-rect.left)/rect.width*W,my=(e.clientY-rect.top)/rect.height*H;const factor=e.deltaY<0?1.12:.89;const next=Math.max(.7,Math.min(5,zoom*factor));setPan(p=>({x:mx-(mx-p.x)*next/zoom,y:my-(my-p.y)*next/zoom}));setZoom(next)}
 const pointers=useRef<Map<number,{x:number;y:number}>>(new Map());
 const moved=useRef(false);
 function onPointerDown(e:React.PointerEvent<SVGSVGElement>){e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===1){moved.current=false;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};}if(pointers.current.size===2){const p=[...pointers.current.values()];pinch.current={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),zoom}}}
 function onPointerMove(e:React.PointerEvent<SVGSVGElement>){pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2&&pinch.current){const p=[...pointers.current.values()];const d=Math.max(1,Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y));setZoom(Math.max(.7,Math.min(5,pinch.current.zoom*d/pinch.current.distance)));return}if(!drag.current||drag.current.id!==e.pointerId)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>4)moved.current=true;setPan({x:drag.current.px+dx,y:drag.current.py+dy})}
 function onPointerUp(e?:React.PointerEvent<SVGSVGElement>){if(e)pointers.current.delete(e.pointerId);if(pointers.current.size<2)pinch.current=null;if(pointers.current.size===0)drag.current=null}
 function distance(a:PointerEvent,b:PointerEvent){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}
 function detail(){
  if(!nation)return <div className='empty-panel'>Select a country directly on the map.</div>;
  if(tab==='Diplomacy')return <><h3>Foreign Relations</h3>
<div className='diplomacy-chat'><label>Diplomatic channel<select value={diplomacyTarget} onChange={e=>setDiplomacyTarget(e.target.value)}><option value=''>Choose nation…</option>{Object.values(worldState.nations).filter(n=>n.id!==nation.id).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,80).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label>{diplomacyTarget&&<><div className='chat-log'>{diplomacyLog.filter(x=>x.speaker===nation.name||x.speaker===worldState.nations[diplomacyTarget]?.name).slice(-6).map((m,i)=><div className='chat-line' key={i}><b>{m.speaker}</b><span>{m.text}</span></div>)}</div><form className='chat-compose' onSubmit={e=>{e.preventDefault();if(!diplomacyDraft.trim())return;const target=worldState.nations[diplomacyTarget];const rel=nation.relations[diplomacyTarget]??0;const text=diplomacyDraft.trim();const reply=rel>50?'We are prepared to discuss closer cooperation, provided your proposal remains consistent with our interests.':rel<-40?'Your proposal is received with considerable suspicion. We will require concrete guarantees.':'We will consider the proposal. Our government will weigh the costs and benefits before responding formally.';setDiplomacyLog(l=>[...l,{speaker:nation.name,text},{speaker:target?.name??'Foreign government',text:reply}]);setDiplomacyDraft('');quick('relations '+(target?.name??diplomacyTarget))}}><input value={diplomacyDraft} onChange={e=>setDiplomacyDraft(e.target.value)} placeholder='Write a diplomatic message…'/><button>Send</button></form></>}</div><div className='row'><span>Alliances</span><b>{nation.alliances.length}</b></div><div className='row'><span>Wars</span><b>{nation.wars.length}</b></div>{Object.entries(nation.relations).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,v])=><div className='row' key={id}><span>{worldState.nations[id]?.name??id}</span><b>{v}</b></div>)}<div className='actions'><button onClick={()=>quick('relations France')}>Improve France</button><button onClick={()=>quick('relations Germany')}>Improve Germany</button><button onClick={()=>quick('ally France')}>Alliance France</button><button onClick={()=>quick('trade France')}>Trade France</button></div></>;
  if(tab==='Economy'||tab==='Production')return <><h3>Economic Command</h3><div className='mini-grid'><Metric title='GDP' value={formatBig(nation.gdp)+' B'}/><Metric title='Treasury' value={formatBig(nation.treasury)+' B'}/><Metric title='Industry' value={String(nation.industrialCapacity)}/><Metric title='Tax' value={pct(worldState.economy[nation.id]?.taxRate??.2)}/></div><div className='actions'><button onClick={()=>quick('build industry')}>Build Industry</button><button onClick={()=>quick('build infrastructure')}>Infrastructure</button><button onClick={()=>quick('tax 15')}>Tax 15%</button><button onClick={()=>quick('tax 30')}>Tax 30%</button></div></>;
  if(tab==='Military')return <><h3>Armed Forces</h3><div className='row'><span>Visible formations</span><b>{Object.values(worldState.units).filter(u=>u.nation===nation.id).length}</b></div><div className='mini-grid'><Metric title='Manpower' value={formatBig(nation.manpower)+' M'}/><Metric title='Readiness' value={String(Math.round(worldState.military[nation.id]?.readiness??50))}/><Metric title='Supply' value={pct(worldState.military[nation.id]?.supply??1)}/><Metric title='War Support' value={String(Math.round(worldState.military[nation.id]?.warSupport??50))}/><Metric title='Logistics' value={String(Math.round(worldState.military[nation.id]?.logistics??50))}/><Metric title='Fuel' value={String(Math.round(worldState.military[nation.id]?.fuel??100))}/><Metric title='Equipment' value={String(Math.round(worldState.military[nation.id]?.equipmentStock??100))}/><Metric title='Command' value={String(Math.round(worldState.military[nation.id]?.commandCapacity??100))}/></div><h4>Operational formations</h4>{Object.values(worldState.units).filter(u=>u.nation===nation.id).slice(0,12).map(u=><div className='row' key={u.id}><span>{u.name}<small>{u.order??'hold'} · {u.status??'ready'} · {u.territory?safeNationName(worldState,u.territory):'home'}</small></span><b>{Math.round(u.organization)} org</b></div>)}<div className='actions'><button onClick={()=>quick('mobilize')}>Mobilize</button><button onClick={()=>quick('recruit 5000')}>Recruit</button><button onClick={()=>quick('demobilize')}>Demobilize</button><button onClick={()=>quick('war Germany')}>War: Germany</button><button onClick={()=>quick('attack Germany')}>Attack Germany</button><button onClick={()=>quick('defend')}>Defend</button><button onClick={()=>quick('hold')}>Hold</button></div></>;
  if(tab==='Politics')return <><h3>Political State</h3><div className='row'><span>Ideology</span><b>{nation.ideology}</b></div><div className='row'><span>Strategic goals</span><b>{nation.politicalGoals.join(' · ')}</b></div><div className='mini-grid'><Metric title='Government' value={nation.government}/><Metric title='Stability' value={String(Math.round(nation.stability))}/><Metric title='Legitimacy' value={String(Math.round(nation.legitimacy))}/><Metric title='Laws' value={String(nation.laws.length)}/></div></>;
  if(tab==='Population')return <><h3>Population</h3><div className='mini-grid'><Metric title='Population' value={formatBig(nation.population)+' M'}/><Metric title='Manpower rate' value={pct(nation.manpowerRate)}/><Metric title='Urbanization' value={String(Math.round((worldState.mapEntities[nation.id]?.ratios.urbanization??.3)*100))+'%'}/><Metric title='Literacy' value={String(Math.round(makeNation(nation.id,nation.name).literacy))+'%'}/></div></>;
  if(tab==='Technology')return <><h3>Research Portfolio</h3>{(nation.technology.length?nation.technology:['Agriculture','Basic Industry','Logistics','Communications']).map(t=><div className='row' key={t}><span>{t}</span><b>ACTIVE</b></div>)}<button className='full-button' onClick={()=>quick('research '+(nation.technology.length+1))}>Fund Research</button></>;
  if(tab==='Territory')return <>{selectedRegion&&worldState.mapEntities[selectedRegion]&&<div className='region-focus'><div className='eyebrow'>{hierarchyPath(worldState.mapEntities,selectedRegion).map(e=>e.name).join(' / ')}</div><h3>{worldState.mapEntities[selectedRegion].name}</h3><div className='mini-grid'><Metric title='Population' value={(worldState.mapEntities[selectedRegion].population/1e6).toFixed(2)+' M'}/><Metric title='Development' value={worldState.mapEntities[selectedRegion].development.toFixed(0)}/><Metric title='Infrastructure' value={worldState.mapEntities[selectedRegion].infrastructure.toFixed(0)}/><Metric title='Owner' value={worldState.nations[worldState.mapEntities[selectedRegion].owner]?.name??'—'}/><Metric title='Controller' value={worldState.nations[worldState.mapEntities[selectedRegion].controller]?.name??'—'}/><Metric title='Density' value={Math.round(worldState.mapEntities[selectedRegion].ratios.density).toLocaleString()+' / km²'}/></div><button onClick={()=>setSelectedRegion(worldState.mapEntities[selectedRegion].parentId??null)}>Back one level</button>{worldState.mapEntities[selectedRegion].children.length>0&&<><h4>Localities</h4>{worldState.mapEntities[selectedRegion].children.map(id=>{const child=worldState.mapEntities[id];return child?<button className='region-button' key={id} onClick={()=>setSelectedRegion(id)}>{child.name}<span>{child.category}</span></button>:null})}</>}</div>}<h3>Strategic Geography</h3><div className='row'><span>Capital</span><b>{nation.capital}</b></div><div className='row'><span>Major cities</span><b>{nation.majorCities.join(' · ')}</b></div><div className='row'><span>Regions</span><b>{nation.strategicRegions.join(' · ')}</b></div><h3>Strategic Regions</h3>{(worldState.mapEntities[nation.id]?.children??[]).map(id=><button className='region-button' key={id} onClick={()=>setSelectedRegion(id)}>{worldState.mapEntities[id]?.name??id}<span>{Math.round(worldState.mapEntities[id]?.development??0)} dev</span></button>)}<h3>Resource Base</h3>{Object.entries(nation.resources).map(([k,v])=><div className='row' key={k}><span>{k}</span><b>{Math.round(v)}</b></div>)}</>;
  if(tab==='Advisor')return <><h3>Strategic Advisor</h3><p className='muted'>The advisor reads the current state and identifies pressures. It does not choose for you.</p>{lastInterpretation&&<div className='advisor-box'><b>Latest command interpretation</b><p>{lastInterpretation.interpretation}</p><small>{lastInterpretation.domains.join(' · ')} · confidence {Math.round(lastInterpretation.confidence*100)}%</small></div>}<div className='advisor-box'><b>Situation</b><p>{nation.wars.length?'Active war requires attention to supply, readiness and manpower. ':''}{nation.stability<45?'Domestic stability is currently under strain. ':''}{nation.treasury<0?'Treasury pressure is elevated. ':''}{nation.wars.length===0&&nation.stability>=45&&nation.treasury>=0?'No immediate systemic crisis is dominant.':''}</p><b>Priority signals</b>{[...nation.wars.length?['War and logistics']:[],...(nation.stability<55?['Political stability']:[]),...(nation.treasury<0?['Fiscal pressure']:[]),...(Object.values(nation.relations).filter(v=>v<-40).length?['Diplomatic tensions']:[])].map(x=><div className='row' key={x}><span>{x}</span><b>MONITOR</b></div>)}</div><button className='full-button' onClick={()=>setLog(l=>['Advisor report generated for '+nation.name+'.',...l].slice(0,12))}>Refresh Assessment</button></>;
 if(tab==='Timeline')return <><h3>World Timeline</h3><div className='timeline-legend'><span>● Major event</span><span>● Player action</span><span>● World development</span></div><p className='muted'>Chronological record of player actions, major events and simulation reports. Longer jumps produce denser history; major events remain highlighted.</p><div className='timeline-list'>{[...worldState.news].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,60).map(n=><div className={'timeline-item importance-'+n.importance} key={n.id}><span className='timeline-date'>{n.date}</span><div><b>{n.title}</b><p>{n.summary}</p><small>{n.category.toUpperCase()} · {n.source}</small></div></div>)}{worldState.scenario.historyLog.slice().reverse().slice(0,30).map((x,i)=><div className='timeline-item player-action' key={'h-'+i}><span className='timeline-date'>ACTION</span><div><b>Player directive</b><p>{x}</p></div></div>)}</div></>;
 if(tab==='News')return <><h3>World News & Intelligence Feed</h3><div className='news-filters'><button onClick={()=>setNewsFilter('all')}>All</button><button onClick={()=>setNewsFilter('major')}>Major</button><button onClick={()=>setNewsFilter('military')}>Military</button><button onClick={()=>setNewsFilter('diplomatic')}>Diplomatic</button><button onClick={()=>setNewsFilter('economic')}>Economic</button></div><div className='row'><span>Reports generated</span><b>{worldState.news.length}</b></div><div className='news-list'>{(newsFilter==='all'?worldState.news:newsFilter==='major'?worldState.news.filter(n=>n.importance>=6):worldState.news.filter(n=>n.category===newsFilter)).slice(0,40).map(n=><div className={'news-item importance-'+n.importance} key={n.id}><div><b>{n.title}</b><small>{n.date} · {n.category.toUpperCase()} · {n.source}</small></div><p>{n.summary}</p></div>)}</div></>;
  if(tab==='Commands')return <><h3>Command Reference</h3><p className='muted'>Every supported command is listed here. You can click an action or type the same command into the command bar.</p><div className='command-grid'>{['build industry','build infrastructure','build dockyard','mobilize','demobilize','recruit 5000','deploy Germany','move Germany','attack Germany','defend','support Germany','hold','research Logistics','tax 15','tax 30','relations France','relations Germany','ally France','trade France','sanction Germany','lift sanction Germany','war Germany','peace Germany','help'].map(x=><button key={x} onClick={()=>quick(x)}>{x}</button>)}</div></>;
 if(tab==='History')return <><h3>Historical Archive</h3><p className='muted'>Worldforge now carries a unified historical knowledge layer for events, places and people alongside the polity archive. Records are encyclopedia context, not deterministic simulation scripts.</p><input value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)} placeholder='Search events, cities, rulers, battles, treaties…'/><div className='mini-grid'><Metric title='Polities' value={String(Object.keys(historicalPolities).length)}/><Metric title='Events' value={String(historicalRecords.filter(r=>r.kind==='event').length)}/><Metric title='Places' value={String(historicalRecords.filter(r=>r.kind==='place').length)}/><Metric title='People' value={String(historicalRecords.filter(r=>r.kind==='person').length)}/></div><div className='history-list'>{(historyQuery?searchHistoricalRecords(historyQuery):historicalRecords).slice(0,60).map(r=><div className='row' key={r.id}><span><b>{r.name}</b><small>{r.kind.toUpperCase()} · {r.region} · {r.tags.slice(0,4).join(' · ')}</small><small>{r.description}</small></span><b>{r.start??'—'}{r.end!==undefined&&r.end!==r.start?'–'+r.end:''}</b></div>)}</div></>;
 if(tab==='Intelligence')return <><h3>Intelligence</h3><div className='mini-grid'><Metric title='Recon' value='50'/><Metric title='Counterintel' value='50'/><Metric title='Network' value='25%'/><Metric title='Deception' value='20'/></div><p className='muted'>Intelligence is intentionally uncertain. Reports are derived from the live diplomatic, military and economic state rather than revealing hidden values automatically.</p><div className='actions'><button onClick={()=>quick('research Intelligence Network')}>Expand Intelligence Network</button><button onClick={()=>setLog(l=>['Intelligence report generated for '+nation.name+'.',...l].slice(0,12))}>Generate Report</button></div></>;
  return <><h3>{nation.name}</h3><p className='muted'>The map is the primary interface. Tap another country to inspect it. Player control changes only through Assume Role. Use free-text commands and time jumps for government, economy, diplomacy and military actions.</p><div className='mini-grid'><Metric title='Population' value={formatBig(nation.population)+' M'}/><Metric title='GDP' value={formatBig(nation.gdp)+' B'}/><Metric title='Industry' value={String(nation.industrialCapacity)}/><Metric title='Stability' value={String(Math.round(nation.stability))}/></div></>;
 }
 if(screen==='launcher'){
  const presets=loadPresets();
  return <main className='launcher'><div className='launcher-card'><div className='eyebrow'>GRAND STRATEGY WORLD SIMULATOR</div><h1>WORLDFORGE</h1><p className='muted'>Choose a campaign before entering the simulation. Saved campaigns and custom presets stay on this device.</p><div className='preset-section'><h2>Built-in Presets</h2><div className='save-list'>{builtInPresets.map(p=><button key={p.id} onClick={()=>startPreset(p)}><b>{p.name}</b><span>{p.date} · {p.description}</span></button>)}</div></div><div className='launch-grid'><section><h2>Resume</h2><button className='hero-button' onClick={resume}>Resume Saved Campaign</button><div className='save-list'>{saves.length?saves.map((s,i)=><button key={i} onClick={()=>enter(s.state)}><b>{s.name}</b><span>{s.date}</span></button>):<div className='muted'>No manual saves yet.</div>}</div></section><section><h2>New Preset</h2><label>Scenario name<input value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder='My World'/></label><label>Start date<input type='date' value={presetDate} onChange={e=>setPresetDate(e.target.value)}/></label><label>Player nation<select value={presetNation} onChange={e=>setPresetNation(e.target.value)}>{countries.map(f=>{const id=mapFeatureId(f,countries.indexOf(f));return <option key={id} value={id}>{makeNation(id,f.properties?.name??'Unknown').name}</option>})}</select></label><div className='actions'><button className='hero-button' onClick={newGame}>Start New Simulation</button><button onClick={createPreset}>Save Preset</button></div></section></div>{presets.length>0&&<section className='preset-section'><h2>Saved Presets</h2><div className='save-list'>{presets.map(p=><button key={p.id} onClick={()=>startPreset(p)}><b>{p.name}</b><span>{p.date} · {p.state.nations[p.playerNation]?.name??p.playerNation}</span></button>)}</div></section>}<div className='muted'>Country geography is bundled with the game. Detailed Admin-1 provinces and city data are packaged into the static build; gameplay uses only local assets.</div></div></main>;
 }
 const liveReports=worldState.news.slice(0,3);
 return <main className='game-shell'>
  <svg ref={svgRef} viewBox={'0 0 '+W+' '+H} className='map-stage' onWheel={onWheel} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp}>
   <rect width={W} height={H} className='ocean'/>
   <g transform={'translate('+pan.x+' '+pan.y+') translate('+W/2+' '+H/2+') scale('+zoom+') translate('+(-W/2)+' '+(-H/2)+')'}>
    {visibleAdmin1.map((f,i)=>{const p=f.properties??{},rid='admin1-'+String(p.adm1_code??i).replace(/[^a-zA-Z0-9_-]/g,'-'),e=worldState.mapEntities[rid],d=path(f)||'';return <path key={rid} d={d} className={'admin1 '+(selectedRegion===rid?'active':'')} onClick={(ev)=>{ev.stopPropagation();if(!moved.current&&e){setSelectedRegion(rid);setTab('Territory');setShowMenu(true)}}}><title>{e?.name??String(p.name??'Province')}</title></path>})}
    {zoom>1.05&&warLines.map(l=><line key={l.a+'-'+l.b} x1={l.ax} y1={l.ay} x2={l.bx} y2={l.by} className='front-line'><title>{safeNationName(worldState,l.a)} ↔ {safeNationName(worldState,l.b)}</title></line>)}
    {visibleCities.map((f,i)=>{const p=f.properties??{},coords=f.geometry?.coordinates as [number,number],name=String(p.name??'City'),pop=Number(p.pop_max??p.pop_min??0);if(!coords||!Number.isFinite(coords[0]))return null;const [x,y]=projection(coords)??[NaN,NaN];return Number.isFinite(x)&&Number.isFinite(y)?<g key={'city-'+String(p.ne_id??i)} className='real-city' onClick={e=>{e.stopPropagation();const hit=Object.values(worldState.mapEntities).filter(e=>e.category==='city'&&e.name===name).sort((a,b)=>Math.hypot(a.centroid[0]-coords[0],a.centroid[1]-coords[1])-Math.hypot(b.centroid[0]-coords[0],b.centroid[1]-coords[1]))[0];if(hit){setSelectedRegion(hit.id);setTab('Territory');setShowMenu(true)}}}><circle cx={x} cy={y} r={Math.max(1.5,Math.min(4,1.5+Math.log10(Math.max(10,pop))*0.55))} className='city-marker'/><text x={x+4} y={y+3} className='city-label'>{name}</text></g>:null})}
    {mapMode==='history'&&historicalFeatures.map((f:any,i:number)=>{const p=f.properties??{},name=String(p.Name??p.name??'Historical polity'),d=path(f)||'';return <path key={String(f.id??i)} d={d} className='historical-polygon' onClick={e=>e.stopPropagation()}><title>{name} · {p.FromYear??'?'}–{p.ToYear??'?'}</title></path>})}
    {countries.map((f,i)=>{const id=mapFeatureId(f,i),mapName=f.properties?.name??'Unknown',live=worldState.nations[id],profile=getWorldProfile(id,mapName),base=makeNation(id,profile?.name??mapName),n=live?({...base,...live} as NationState):base,root=worldState.mapEntities[id],displayId=root?.controller??root?.owner??id,displayNation=worldState.nations[displayId]??n,cent=path.centroid(f),relation=worldState.nations[worldState.playerNation??'']?.relations[displayId]??0;const fill=mapMode==='history'?'transparent':mapMode==='economy'?'hsl('+Math.round(displayNation.gdp%360)+' 45% '+Math.max(25,Math.min(65,30+displayNation.industrialCapacity/3))+'%)':mapMode==='military'?'hsl('+Math.round(5+(worldState.military[displayId]?.readiness??displayNation.industrialCapacity)*1.4)+' 48% '+Math.max(28,Math.min(68,32+(worldState.military[displayId]?.readiness??displayNation.industrialCapacity)/2))+'%)':mapMode==='resources'?'hsl('+Math.round(70+(displayNation.resources?.oil??displayNation.resources?.iron??50)/2)+' 40% '+Math.max(25,Math.min(70,30+(displayNation.resources?.oil??50)/2))+'%)':mapMode==='diplomacy'?'hsl('+Math.round(120+relation*1.2)+' 42% 42%)':identityColor(worldState.political.identities[displayId]?.colorKey??displayId);return <g key={id} onClick={(e)=>{e.stopPropagation();if(!moved.current)selectCountry(id,displayNation.name)}}><path d={path(f)||''} style={{fill}} className={'country '+(worldState.playerNation===id?'selected ':'')+(selectedNationId===id?'inspected':'')}><title>{displayNation.name}{displayId!==id?' · controlled by '+displayNation.name:''}</title></path>{zoom>1.15&&Number.isFinite(cent[0])&&Number.isFinite(cent[1])&&mapMode!=='history'&&<><text x={cent[0]} y={cent[1]} className='nation-label'>{displayNation.name}</text><text x={cent[0]} y={cent[1]-10} className='capital-marker'>★</text></>}{zoom>1.8&&Number.isFinite(cent[0])&&Number.isFinite(cent[1])&&mapMode!=='history'&&<g>{n.majorCities.slice(0,4).map((city,j)=><circle key={city} cx={cent[0]+(j-1.5)*8} cy={cent[1]+((j%2)*8-4)} r='2.2' className='city-marker'><title>{city}</title></circle>)}</g>}</g>})}
   </g>
  </svg>
  <header className='floating top-controls'><button onClick={()=>setShowMenu(!showMenu)}>☰</button><div><div className='eyebrow'>WORLDFORGE · {tab.toUpperCase()}</div><strong>{worldState.date}</strong><span className='scenario-status'>Divergence {Math.round(worldState.scenario.divergence)}%</span></div><div className='time-controls'><button onClick={()=>setPaused(!paused)}>{paused?'▶':'Ⅱ'}</button><button onClick={skipToMajor}>Next Major</button><button onClick={()=>advanceBy(7)}>+1W</button><button onClick={()=>advanceBy(30)}>+1M</button><button onClick={()=>advanceBy(365)}>+1Y</button><input aria-label='Custom days' type='number' min='1' max='3650' value={customDays} onChange={e=>setCustomDays(+e.target.value||1)} /><button onClick={()=>advanceBy(customDays)}>+Days</button><select value={speed} onChange={e=>setSpeed(+e.target.value)}>{speeds.map(x=><option key={x} value={x}>{x}× auto</option>)}</select><button onClick={save}>Save</button></div></header>
  <div className='floating map-hint'>Pinch / scroll to zoom · drag to pan · tap a country · zoom in for provinces · {geoStatus==='ready'?'Admin-1 geography ready':'Loading regional geography…'} · {mapMode==='history'?(historicalStatus==='ready'?'Historical geography ready':historicalStatus==='loading'?'Loading historical geography…':'Historical geography unavailable'):'Live simulation map'} · {worldState.news.length} reports</div>
  {lastInterpretation&&<section className='floating interpretation-card'><div className='eyebrow'>AI ORDER INTERPRETATION · {Math.round(lastInterpretation.confidence*100)}%</div><b>{lastInterpretation.objective}</b><p>{lastInterpretation.interpretation}</p><div className='interpretation-tags'>{lastInterpretation.domains.map(d=><span key={d}>{d}</span>)}{lastInterpretation.targets.map(id=><span key={id}>@{worldState.nations[id]?.name??id}</span>)}{lastInterpretation.constraints.map(x=><span key={x}>{x}</span>)}</div><button onClick={()=>setLastInterpretation(null)}>Dismiss</button></section>}<div className='floating map-modes'><span>MAP</span>{(['political','economy','military','resources','diplomacy','history'] as const).map(m=><button className={mapMode===m?'active':''} onClick={()=>setMapMode(m)} key={m}>{m}</button>)}</div>
  <nav className='floating tab-dock'>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>{setTab(t);if(!selected){const id=worldState.playerNation??'840',p=worldState.nations[id];if(p)setSelected(makeNation(id,p.name));}setShowMenu(true)}} key={t}>{t}</button>)}</nav>
  {showMenu&&<div className='floating menu-pop'>
 <button onClick={()=>setScreen('launcher')}>Campaign / Presets</button>
 <button onClick={()=>{setChangeNationOpen(true);setShowMenu(true)}}>Change Player Nation</button>
 <button onClick={()=>{setTab('Overview');setShowMenu(true)}}>Open Overview</button>
 <button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Center Map</button>
 <button onClick={save}>Save Campaign</button>
 <button onClick={()=>setShowMenu(false)}>Close</button>
 {changeNationOpen&&<div className='nation-switcher'><h3>Assume a Different Nation</h3><p className='muted'>Changing this role is deliberate and only happens from this menu. Map clicks no longer transfer player control.</p><select value={worldState.playerNation??''} onChange={e=>{const id=e.target.value;setWorldState(s=>({...s,playerNation:id}));setSelectedNationId(id);setSelected(makeNation(id,safeNationName(worldState,id)));setSelectedRegion(null);setTab('Overview')}}>{Object.values(worldState.nations).sort((a,b)=>a.name.localeCompare(b.name)).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select><button onClick={()=>setChangeNationOpen(false)}>Assume Role</button></div>}
 </div>}
  {selected&&<aside className='floating info-panel'><div className='panel-title'><div><div className='eyebrow'>{viewedNationId===worldState.playerNation?'PLAYER POLITY':'SELECTED NATION'}</div><h2>{nation?.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></div>
 {viewedNationId!==worldState.playerNation&&<button className='full-button' onClick={()=>{setWorldState(s=>({...s,playerNation:viewedNationId}));setSelectedNationId(viewedNationId);setLog(l=>['Player role changed to '+(worldState.nations[viewedNationId]?.name??viewedNationId),...l].slice(0,12))}}>Assume Role as {nation?.name}</button>}
 {detail()}</aside>}
  {liveReports.length>0&&<section className='floating live-report-stack' aria-live='polite'><div className='eyebrow'>LIVE REPORTS</div>{liveReports.map(report=><article className='live-report' key={report.id}><div className='live-report-head'><b>{report.title}</b><small>{report.date} · {report.category.toUpperCase()}</small></div><p>{report.summary}</p><div className='report-tags'>{(report.mentionedNations?.length?report.mentionedNations:[report.relatedNation].filter(Boolean) as string[]).map(id=><span className='nation-tag' key={id}>@{worldState.nations[id]?.name??id}</span>)}</div></article>)}</section>}
  {activeEvents.length>0&&<div className='floating event-stack'>{activeEvents.slice(0,2).map(e=><div className='event-card' key={e.id}><b>{e.title}</b><p>{e.description}</p><div className='actions'>{e.options.map((o,i)=><button key={o} onClick={()=>{const s=structuredClone(worldState);const r=applyEventEffects(s,e.id,i);if(r.ok){s.scenario.divergence=Math.min(100,s.scenario.divergence+1);s.scenario.historyLog.push('event:'+e.id+':'+i);}setWorldState(s);setLog(l=>[r.message,...l].slice(0,12))}}>{o}</button>)}</div></div>)}</div>}
  {lastInterpretation&&<section className='floating interpretation-card'><div className='eyebrow'>AI INTERPRETATION · {Math.round(lastInterpretation.confidence*100)}%</div><b>{lastInterpretation.objective}</b><p>{lastInterpretation.interpretation}</p>{lastInterpretation.targets.length>0&&<div className='report-tags'>{lastInterpretation.targets.map(id=><span className='nation-tag' key={id}>@{safeNationName(worldState,id)}</span>)}</div>}</section>}
<form className='floating command-bar' onSubmit={e=>{e.preventDefault();if(command.trim())quick(command);setCommand('')}}><input value={command} onChange={e=>setCommand(e.target.value)} placeholder='What do you want your government to do?'/><button>Issue Order</button></form>
  <div className='floating zoom-dock'><button onClick={()=>setZoom(z=>Math.min(5,z*1.2))}>+</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.max(.7,z/1.2))}>−</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Reset</button></div>
  {log.length>0&&<div className='floating log-dock'>{log.slice(0,4).map((x,i)=><div key={i}>{x}</div>)}</div>}
 </main>
}
function Metric({title,value}:{title:string;value:string}){return <div className='metric'><span>{title}</span><b>{value}</b></div>}
