'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {geoNaturalEarth1,geoPath} from 'd3-geo';
import {feature} from 'topojson-client';
import world from 'world-atlas/countries-110m.json';
import {makeNation,NationState,START_DATE} from '../lib/game-data';
import {getWorldProfile} from '../lib/world-database';
import {registerAdmin1Features} from '../lib/region-data';
import {historicalPolities,searchHistoricalPolities} from '../lib/historical-polities';
import {createWorldState,advanceWorld,issueCommand,ensureNationSystems,syncPoliticalMap,applyEventEffects} from '../engine';
import type {WorldState} from '../engine';

const countries:any[]=(((feature(world as any,(world as any).objects.countries) as any).features??[]) as any[]);
const speeds=[1,2,5,10,20];
const tabs=['Overview','Politics','Economy','Diplomacy','Military','Intelligence','Production','Technology','Population','Territory','History'];
function mapFeatureId(f:any,index:number){const raw=f?.id; if(raw!==undefined&&raw!==null&&String(raw)!=='')return String(raw);const label=String(f?.properties?.name??'unit-'+index).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return 'unit-'+(label||index)}
type Preset={id:string;name:string;description:string;date:string;playerNation:string;state:WorldState};

function seedWorld(date=START_DATE,playerNation?:string):WorldState{
 const state=createWorldState(date);
 for(const f of countries){
  const id=mapFeatureId(f,countries.indexOf(f)), mapName=f.properties?.name??'Unknown', db=getWorldProfile(id,mapName), n=makeNation(id,db?.name??mapName);
  state.nations[id]={id:n.id,name:n.name,government:n.government,population:n.population,gdp:n.gdp,treasury:n.gdp*.15,debt:0,stability:n.stability,legitimacy:65,industrialCapacity:n.industry,civilianFactories:Math.max(5,Math.round(n.industry*.45)),militaryFactories:Math.max(2,Math.round(n.industry*.14)),dockyards:Math.max(1,Math.round(n.industry*.05)),manpower:n.population*n.manpowerRate,research:1,technology:['Agriculture','Basic Industry'],laws:[],relations:{},alliances:[],wars:[],ideology:n.ideology,politicalGoals:n.politicalGoals,resources:n.resources,strategicRegions:n.strategicRegions,majorCities:n.majorCities,historicalNotes:n.historicalNotes};
  const baseCentroid:[number,number]=[0,0]; const areaKm2=1;
  state.mapEntities[id]={id,name:n.name,category:'country',controller:id,owner:id,areaKm2,population:n.population*1e6,mapSource:'bundled-world-atlas',centroid:baseCentroid,geometryKey:id,children:[],adjacency:[],development:n.industry,infrastructure:50,ratios:{childrenPerParent:0,populationShare:1,areaShare:1,urbanization:n.urbanization/100,density:n.population}};

  ensureNationSystems(state,state.nations[id]);
 }
 // Give every mapped nation a complete bilateral diplomacy matrix instead of leaving most panels empty.
 const ids=Object.keys(state.nations);
 for(const id of ids){
  const n=state.nations[id];
  for(const other of ids){if(other===id)continue; const a=Number(id)||0,b=Number(other)||0; n.relations[other]=Math.max(-100,Math.min(100,((a*31+b*17)%81)-40));}
  state.diplomacy[id].relations={...n.relations};
 }
 syncPoliticalMap(state); state.playerNation=playerNation??'840'; return state;
}
function pct(v:number){return Math.round(v*100)+'%'}
function identityColor(key:string){let h=0;for(const ch of key)h=(h*31+ch.charCodeAt(0))>>>0;return 'hsl('+h%360+' 38% 42%)'}
function formatBig(v:number){return v>=100?v.toFixed(0):v.toFixed(1)}

export default function GameShell(){
 const [screen,setScreen]=useState<'launcher'|'game'>('launcher');
 const [worldState,setWorldState]=useState<WorldState>(()=>seedWorld());
 const [selected,setSelected]=useState<NationState|null>(null),[selectedRegion,setSelectedRegion]=useState<string|null>(null);
 const [paused,setPaused]=useState(true),[speed,setSpeed]=useState(1),[tab,setTab]=useState('Overview');
 const [command,setCommand]=useState(''),[log,setLog]=useState<string[]>([]),[historyQuery,setHistoryQuery]=useState('');
 const [saves,setSaves]=useState<{name:string;date:string;state:WorldState}[]>([]);
 const [presetName,setPresetName]=useState(''),[presetDate,setPresetDate]=useState(START_DATE),[presetNation,setPresetNation]=useState('840');
 const [showMenu,setShowMenu]=useState(false),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[mapMode,setMapMode]=useState<'political'|'economy'|'military'|'resources'>('political');
 const [admin1Features,setAdmin1Features]=useState<any[]>([]),[cityFeatures,setCityFeatures]=useState<any[]>([]),[geoStatus,setGeoStatus]=useState<'loading'|'ready'|'error'>('loading');
 const svgRef=useRef<SVGSVGElement|null>(null);
 const drag=useRef<{id:number;x:number;y:number;px:number;py:number}|null>(null);
 const pinch=useRef<{distance:number;zoom:number}|null>(null);
 const W=1200,H=650;
 const projection=useMemo(()=>geoNaturalEarth1().fitSize([W,H],{type:'FeatureCollection',features:countries} as any),[]);
 const path=useMemo(()=>geoPath(projection),[projection]);
 const liveNation=worldState.playerNation?worldState.nations[worldState.playerNation]:undefined;
 const nation=liveNation?({...makeNation(liveNation.id,liveNation.name),...liveNation} as NationState):undefined;
 const activeEvents=worldState.events.filter(e=>!e.resolved);
 const visibleAdmin1=zoom>1.12?admin1Features:[];
 const visibleCities=zoom>2?cityFeatures:[];

 useEffect(()=>{try{const raw=localStorage.getItem('worldforge-saves');if(raw)setSaves(JSON.parse(raw));}catch{}},[]);
 useEffect(()=>{let alive=true;(async()=>{try{const base=new URL('./data/',window.location.href);const [a,cs]=await Promise.all([fetch(new URL('admin1.json',base)).then(r=>{if(!r.ok)throw new Error('admin1 '+r.status);return r.json()}),fetch(new URL('cities.json',base)).then(r=>{if(!r.ok)throw new Error('cities '+r.status);return r.json()})]);if(!alive)return;setAdmin1Features(a.features??[]);setCityFeatures(cs.features??[]);setWorldState(s=>{const next=structuredClone(s);registerAdmin1Features(next,a.features??[],cs.features??[]);return next});setGeoStatus('ready');}catch(err){console.error(err);if(alive)setGeoStatus('error')}})();return()=>{alive=false}},[]);
 useEffect(()=>{if(screen!=='game'||paused)return;const id=setInterval(()=>setWorldState(s=>advanceWorld(s,speed)),650);return()=>clearInterval(id)},[screen,paused,speed]);
 useEffect(()=>{if(screen==='game'){try{localStorage.setItem('worldforge-autosave',JSON.stringify(worldState));}catch{}}},[worldState,screen]);

 function enter(state:WorldState){setWorldState(state);const p=state.playerNation??'840';setSelected(makeNation(p,state.nations[p]?.name??'United States'));setScreen('game');setTab('Overview');setPaused(true);setPan({x:0,y:0});setZoom(1)}
 function newGame(){enter(seedWorld(presetDate,presetNation));setLog(['New simulation initialized.'])}
 function resume(){try{const raw=localStorage.getItem('worldforge-save');if(raw){enter(JSON.parse(raw));setLog(['Saved campaign resumed.']);return}}catch{} setLog(['No manual save found.']);}
 function quick(c:string){const s=structuredClone(worldState);const r=issueCommand(s,c,s.playerNation??'');setWorldState(s);setLog(x=>[(r.ok?'✓ ':'✕ ')+r.message,...x].slice(0,12));setShowMenu(true)}
 function selectCountry(id:string,name:string){const live=worldState.nations[id];const profile=getWorldProfile(id,name);const n=live?makeNation(id,profile?.name??live.name):makeNation(id,profile?.name??name);setWorldState(s=>({...s,playerNation:id}));setSelected(n);setSelectedRegion(null);setTab('Overview');setShowMenu(true)}
 function save(){try{localStorage.setItem('worldforge-save',JSON.stringify(worldState));localStorage.setItem('worldforge-save-version','2.0');const entry={name:(worldState.nations[worldState.playerNation??'840']?.name??'Campaign')+' Campaign',date:worldState.date,state:worldState};const next=[entry,...saves.filter(s=>!(s.date===entry.date&&s.name===entry.name))].slice(0,8);localStorage.setItem('worldforge-saves',JSON.stringify(next));setSaves(next);setLog(x=>['Campaign saved on this device.',...x])}catch{setLog(x=>['Save failed.',...x])}}
 function createPreset(){const p:Preset={id:crypto.randomUUID(),name:presetName.trim()||'Custom Scenario',description:'Player-created Worldforge preset',date:presetDate,playerNation:presetNation,state:seedWorld(presetDate,presetNation)};try{const raw=localStorage.getItem('worldforge-presets');const list:Preset[]=raw?JSON.parse(raw):[];list.unshift(p);localStorage.setItem('worldforge-presets',JSON.stringify(list));setLog(['Preset created: '+p.name]);setPresetName('')}catch{}}
 function loadPresets():Preset[]{try{return JSON.parse(localStorage.getItem('worldforge-presets')||'[]')}catch{return[]}}
 const builtInPresets:Preset[]=[{id:'builtin-1936',name:'The World · 1936',description:'Baseline pre-war campaign',date:'1936-01-01',playerNation:'840',state:seedWorld('1936-01-01','840')},{id:'builtin-1939',name:'The World · 1939',description:'Late pre-war campaign',date:'1939-09-01',playerNation:'826',state:seedWorld('1939-09-01','826')},{id:'builtin-1941',name:'The World · 1941',description:'Global-war campaign',date:'1941-06-22',playerNation:'643',state:seedWorld('1941-06-22','643')},{id:'builtin-czech',name:'Czechoslovakia · 1941',description:'Alternate-history Central European campaign',date:'1941-11-13',playerNation:'203',state:seedWorld('1941-11-13','203')}];
 function startPreset(p:Preset){enter(structuredClone(p.state))}
 function onWheel(e:React.WheelEvent){e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();const mx=(e.clientX-rect.left)/rect.width*W,my=(e.clientY-rect.top)/rect.height*H;const factor=e.deltaY<0?1.12:.89;const next=Math.max(.7,Math.min(5,zoom*factor));setPan(p=>({x:mx-(mx-p.x)*next/zoom,y:my-(my-p.y)*next/zoom}));setZoom(next)}
 const pointers=useRef<Map<number,{x:number;y:number}>>(new Map());
 const moved=useRef(false);
 function onPointerDown(e:React.PointerEvent<SVGSVGElement>){e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===1){moved.current=false;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};}if(pointers.current.size===2){const p=[...pointers.current.values()];pinch.current={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),zoom}}}
 function onPointerMove(e:React.PointerEvent<SVGSVGElement>){pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2&&pinch.current){const p=[...pointers.current.values()];const d=Math.max(1,Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y));setZoom(Math.max(.7,Math.min(5,pinch.current.zoom*d/pinch.current.distance)));return}if(!drag.current||drag.current.id!==e.pointerId)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>4)moved.current=true;setPan({x:drag.current.px+dx,y:drag.current.py+dy})}
 function onPointerUp(e?:React.PointerEvent<SVGSVGElement>){if(e)pointers.current.delete(e.pointerId);if(pointers.current.size<2)pinch.current=null;if(pointers.current.size===0)drag.current=null}
 function distance(a:PointerEvent,b:PointerEvent){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}
 function detail(){
  if(!nation)return <div className='empty-panel'>Select a country directly on the map.</div>;
  if(tab==='Diplomacy')return <><h3>Foreign Relations</h3><div className='row'><span>Alliances</span><b>{nation.alliances.length}</b></div><div className='row'><span>Wars</span><b>{nation.wars.length}</b></div>{Object.entries(nation.relations).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,v])=><div className='row' key={id}><span>{worldState.nations[id]?.name??id}</span><b>{v}</b></div>)}<div className='actions'><button onClick={()=>quick('relations France')}>Improve France</button><button onClick={()=>quick('relations Germany')}>Improve Germany</button><button onClick={()=>quick('ally France')}>Alliance France</button><button onClick={()=>quick('trade France')}>Trade France</button></div></>;
  if(tab==='Economy'||tab==='Production')return <><h3>Economic Command</h3><div className='mini-grid'><Metric title='GDP' value={formatBig(nation.gdp)+' B'}/><Metric title='Treasury' value={formatBig(nation.treasury)+' B'}/><Metric title='Industry' value={String(nation.industrialCapacity)}/><Metric title='Tax' value={pct(worldState.economy[nation.id]?.taxRate??.2)}/></div><div className='actions'><button onClick={()=>quick('build industry')}>Build Industry</button><button onClick={()=>quick('build infrastructure')}>Infrastructure</button><button onClick={()=>quick('tax 15')}>Tax 15%</button><button onClick={()=>quick('tax 30')}>Tax 30%</button></div></>;
  if(tab==='Military')return <><h3>Armed Forces</h3><div className='row'><span>Visible formations</span><b>{Object.values(worldState.units).filter(u=>u.nation===nation.id).length}</b></div><div className='mini-grid'><Metric title='Manpower' value={formatBig(nation.manpower)+' M'}/><Metric title='Readiness' value={String(Math.round(worldState.military[nation.id]?.readiness??50))}/><Metric title='Supply' value={pct(worldState.military[nation.id]?.supply??1)}/><Metric title='War Support' value={String(Math.round(worldState.military[nation.id]?.warSupport??50))}/></div><div className='actions'><button onClick={()=>quick('mobilize')}>Mobilize</button><button onClick={()=>quick('recruit 5000')}>Recruit</button><button onClick={()=>quick('demobilize')}>Demobilize</button><button onClick={()=>quick('war Germany')}>War: Germany</button><button onClick={()=>quick('move Germany')}>Move Army → Germany</button></div></>;
  if(tab==='Politics')return <><h3>Political State</h3><div className='row'><span>Ideology</span><b>{nation.ideology}</b></div><div className='row'><span>Strategic goals</span><b>{nation.politicalGoals.join(' · ')}</b></div><div className='mini-grid'><Metric title='Government' value={nation.government}/><Metric title='Stability' value={String(Math.round(nation.stability))}/><Metric title='Legitimacy' value={String(Math.round(nation.legitimacy))}/><Metric title='Laws' value={String(nation.laws.length)}/></div></>;
  if(tab==='Population')return <><h3>Population</h3><div className='mini-grid'><Metric title='Population' value={formatBig(nation.population)+' M'}/><Metric title='Manpower rate' value={pct(nation.manpowerRate)}/><Metric title='Urbanization' value={String(Math.round((worldState.mapEntities[nation.id]?.ratios.urbanization??.3)*100))+'%'}/><Metric title='Literacy' value={String(Math.round(makeNation(nation.id,nation.name).literacy))+'%'}/></div></>;
  if(tab==='Technology')return <><h3>Research Portfolio</h3>{(nation.technology.length?nation.technology:['Agriculture','Basic Industry','Logistics','Communications']).map(t=><div className='row' key={t}><span>{t}</span><b>ACTIVE</b></div>)}<button className='full-button' onClick={()=>quick('research '+(nation.technology.length+1))}>Fund Research</button></>;
  if(tab==='Territory')return <>{selectedRegion&&worldState.mapEntities[selectedRegion]&&<div className='region-focus'><h3>{worldState.mapEntities[selectedRegion].name}</h3><div className='mini-grid'><Metric title='Population' value={(worldState.mapEntities[selectedRegion].population/1e6).toFixed(2)+' M'}/><Metric title='Development' value={worldState.mapEntities[selectedRegion].development.toFixed(0)}/><Metric title='Infrastructure' value={worldState.mapEntities[selectedRegion].infrastructure.toFixed(0)}/><Metric title='Owner' value={worldState.nations[worldState.mapEntities[selectedRegion].owner]?.name??'—'}/></div><button onClick={()=>setSelectedRegion(null)}>Back to country</button></div>}<h3>Strategic Geography</h3><div className='row'><span>Capital</span><b>{nation.capital}</b></div><div className='row'><span>Major cities</span><b>{nation.majorCities.join(' · ')}</b></div><div className='row'><span>Regions</span><b>{nation.strategicRegions.join(' · ')}</b></div><h3>Strategic Regions</h3>{(worldState.mapEntities[nation.id]?.children??[]).map(id=><button className='region-button' key={id} onClick={()=>setSelectedRegion(id)}>{worldState.mapEntities[id]?.name??id}<span>{Math.round(worldState.mapEntities[id]?.development??0)} dev</span></button>)}<h3>Resource Base</h3>{Object.entries(nation.resources).map(([k,v])=><div className='row' key={k}><span>{k}</span><b>{Math.round(v)}</b></div>)}</>;
  if(tab==='History')return <><h3>Historical Polity Archive</h3><p className='muted'>A separate encyclopedia preserves political entities even when they are not active in this campaign. Scenario activation and simulation state are independent.</p><input value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)} placeholder='Search kingdoms, empires, republics…'/><div className='row'><span>Registry entries</span><b>{Object.keys(historicalPolities).length}</b></div><div className='history-list'>{(historyQuery?searchHistoricalPolities(historyQuery):Object.values(historicalPolities)).slice(0,40).map(p=><div className='row' key={p.id}><span><b>{p.name}</b><small>{p.region} · {p.era}</small></span><b>{p.start??'—'}–{p.end===9999?'present':p.end??'—'}</b></div>)}</div></>;
 if(tab==='Intelligence')return <><h3>Intelligence</h3><div className='mini-grid'><Metric title='Recon' value='50'/><Metric title='Counterintel' value='50'/><Metric title='Network' value='25%'/><Metric title='Deception' value='20'/></div><p className='muted'>Intelligence is intentionally uncertain. Reports are derived from the live diplomatic, military and economic state rather than revealing hidden values automatically.</p><div className='actions'><button onClick={()=>quick('research Intelligence Network')}>Expand Intelligence Network</button><button onClick={()=>setLog(l=>['Intelligence report generated for '+nation.name+'.',...l].slice(0,12))}>Generate Report</button></div></>;
  return <><h3>{nation.name}</h3><p className='muted'>The map is the primary interface. Tap another country to change the player polity, then use the floating command panel for government, economy, diplomacy and military actions.</p><div className='mini-grid'><Metric title='Population' value={formatBig(nation.population)+' M'}/><Metric title='GDP' value={formatBig(nation.gdp)+' B'}/><Metric title='Industry' value={String(nation.industrialCapacity)}/><Metric title='Stability' value={String(Math.round(nation.stability))}/></div></>;
 }
 if(screen==='launcher'){
  const presets=loadPresets();
  return <main className='launcher'><div className='launcher-card'><div className='eyebrow'>GRAND STRATEGY WORLD SIMULATOR</div><h1>WORLDFORGE</h1><p className='muted'>Choose a campaign before entering the simulation. Saved campaigns and custom presets stay on this device.</p><div className='preset-section'><h2>Built-in Presets</h2><div className='save-list'>{builtInPresets.map(p=><button key={p.id} onClick={()=>startPreset(p)}><b>{p.name}</b><span>{p.date} · {p.description}</span></button>)}</div></div><div className='launch-grid'><section><h2>Resume</h2><button className='hero-button' onClick={resume}>Resume Saved Campaign</button><div className='save-list'>{saves.length?saves.map((s,i)=><button key={i} onClick={()=>enter(s.state)}><b>{s.name}</b><span>{s.date}</span></button>):<div className='muted'>No manual saves yet.</div>}</div></section><section><h2>New Preset</h2><label>Scenario name<input value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder='My World'/></label><label>Start date<input type='date' value={presetDate} onChange={e=>setPresetDate(e.target.value)}/></label><label>Player nation<select value={presetNation} onChange={e=>setPresetNation(e.target.value)}>{countries.map(f=>{const id=mapFeatureId(f,countries.indexOf(f));return <option key={id} value={id}>{makeNation(id,f.properties?.name??'Unknown').name}</option>})}</select></label><div className='actions'><button className='hero-button' onClick={newGame}>Start New Simulation</button><button onClick={createPreset}>Save Preset</button></div></section></div>{presets.length>0&&<section className='preset-section'><h2>Saved Presets</h2><div className='save-list'>{presets.map(p=><button key={p.id} onClick={()=>startPreset(p)}><b>{p.name}</b><span>{p.date} · {p.state.nations[p.playerNation]?.name??p.playerNation}</span></button>)}</div></section>}<div className='muted'>Country geography is bundled with the game. Detailed Admin-1 provinces and city data are packaged into the static build; gameplay uses only local assets.</div></div></main>;
 }
 return <main className='game-shell'>
  <svg ref={svgRef} viewBox={'0 0 '+W+' '+H} className='map-stage' onWheel={onWheel} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp}>
   <rect width={W} height={H} className='ocean'/>
   <g transform={'translate('+pan.x+' '+pan.y+') translate('+W/2+' '+H/2+') scale('+zoom+') translate('+(-W/2)+' '+(-H/2)+')'}>
    {visibleAdmin1.map((f,i)=>{const p=f.properties??{},rid='admin1-'+String(p.adm1_code??i).replace(/[^a-zA-Z0-9_-]/g,'-'),e=worldState.mapEntities[rid],d=path(f)||'';return <path key={rid} d={d} className={'admin1 '+(selectedRegion===rid?'active':'')} onClick={(ev)=>{ev.stopPropagation();if(!moved.current&&e){setSelectedRegion(rid);setTab('Territory');setShowMenu(true)}}}><title>{e?.name??String(p.name??'Province')}</title></path>})}
    {visibleCities.map((f,i)=>{const p=f.properties??{},coords=f.geometry?.coordinates as [number,number],name=String(p.name??'City'),pop=Number(p.pop_max??p.pop_min??0);if(!coords||!Number.isFinite(coords[0]))return null;const [x,y]=projection(coords)??[NaN,NaN];return Number.isFinite(x)&&Number.isFinite(y)?<g key={'city-'+String(p.ne_id??i)} className='real-city' onClick={e=>{e.stopPropagation();const hit=Object.values(worldState.mapEntities).find(e=>e.category==='city'&&e.name===name);if(hit){setSelectedRegion(hit.id);setTab('Territory');setShowMenu(true)}}}><circle cx={x} cy={y} r={Math.max(1.5,Math.min(4,1.5+Math.log10(Math.max(10,pop))*0.55))} className='city-marker'/><text x={x+4} y={y+3} className='city-label'>{name}</text></g>:null})}
    {countries.map((f,i)=>{const id=mapFeatureId(f,i),mapName=f.properties?.name??'Unknown',profile=getWorldProfile(id,mapName),n=makeNation(id,profile?.name??mapName),cent=path.centroid(f);return <g key={id} onClick={(e)=>{e.stopPropagation();if(!moved.current)selectCountry(id,n.name)}}><path d={path(f)||''} style={{fill:mapMode==='economy'?'hsl('+Math.round(n.gdp%360)+' 45% '+Math.max(25,Math.min(65,30+n.industrialCapacity/3))+'%)':mapMode==='military'?'hsl('+Math.round(5+n.military*1.4)+' 48% '+Math.max(28,Math.min(68,32+n.military/2))+'%)':mapMode==='resources'?'hsl('+Math.round(70+n.resourcePotential/2)+' 40% '+Math.max(25,Math.min(70,30+n.resourcePotential/2))+'%)':identityColor(worldState.political.identities[id]?.colorKey??id)}} className={'country '+(worldState.playerNation===id?'selected':'')}><title>{n.name}</title></path>{zoom>1.15&&Number.isFinite(cent[0])&&Number.isFinite(cent[1])&&<><text x={cent[0]} y={cent[1]} className='nation-label'>{n.name}</text><text x={cent[0]} y={cent[1]-10} className='capital-marker'>★</text></>}{zoom>1.8&&Number.isFinite(cent[0])&&Number.isFinite(cent[1])&&<g>{n.majorCities.slice(0,4).map((city,j)=><circle key={city} cx={cent[0]+(j-1.5)*8} cy={cent[1]+((j%2)*8-4)} r='2.2' className='city-marker'><title>{city}</title></circle>)}</g>}</g>})}
   </g>
  </svg>
  <header className='floating top-controls'><button onClick={()=>setShowMenu(!showMenu)}>☰</button><div><div className='eyebrow'>WORLDFORGE · {tab.toUpperCase()}</div><strong>{worldState.date}</strong></div><div className='time-controls'><button onClick={()=>setPaused(!paused)}>{paused?'▶':'Ⅱ'}</button><select value={speed} onChange={e=>setSpeed(+e.target.value)}>{speeds.map(x=><option key={x} value={x}>{x}×</option>)}</select><button onClick={save}>Save</button></div></header>
  <div className='floating map-hint'>Pinch / scroll to zoom · drag to pan · tap a country · zoom in for provinces · {geoStatus==='ready'?'Admin-1 geography ready':'Loading regional geography…'}</div><div className='floating map-modes'><span>MAP</span>{(['political','economy','military','resources'] as const).map(m=><button className={mapMode===m?'active':''} onClick={()=>setMapMode(m)} key={m}>{m}</button>)}</div>
  <nav className='floating tab-dock'>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>{setTab(t);if(!selected){const id=worldState.playerNation??'840',p=worldState.nations[id];if(p)setSelected(makeNation(id,p.name));}setShowMenu(true)}} key={t}>{t}</button>)}</nav>
  {showMenu&&<div className='floating menu-pop'><button onClick={()=>setScreen('launcher')}>Campaign / Presets</button><button onClick={()=>{setTab('Overview');setShowMenu(true)}}>Open Overview</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Center Map</button><button onClick={save}>Save Campaign</button><button onClick={()=>setShowMenu(false)}>Close</button></div>}
  {selected&&<aside className='floating info-panel'><div className='panel-title'><div><div className='eyebrow'>PLAYER POLITY</div><h2>{nation?.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></div>{detail()}</aside>}
  {activeEvents.length>0&&<div className='floating event-stack'>{activeEvents.slice(0,2).map(e=><div className='event-card' key={e.id}><b>{e.title}</b><p>{e.description}</p><div className='actions'>{e.options.map((o,i)=><button key={o} onClick={()=>{const s=structuredClone(worldState);const r=applyEventEffects(s,e.id,i);setWorldState(s);setLog(l=>[r.message,...l].slice(0,12))}}>{o}</button>)}</div></div>)}</div>}
  <form className='floating command-bar' onSubmit={e=>{e.preventDefault();if(command.trim())quick(command);setCommand('')}}><input value={command} onChange={e=>setCommand(e.target.value)} placeholder='Issue command…'/><button>Issue</button></form>
  <div className='floating zoom-dock'><button onClick={()=>setZoom(z=>Math.min(5,z*1.2))}>+</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.max(.7,z/1.2))}>−</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Reset</button></div>
  {log.length>0&&<div className='floating log-dock'>{log.slice(0,4).map((x,i)=><div key={i}>{x}</div>)}</div>}
 </main>
}
function Metric({title,value}:{title:string;value:string}){return <div className='metric'><span>{title}</span><b>{value}</b></div>}
