export type PolityEra='ancient'|'medieval'|'early-modern'|'modern'|'unrecognized'|'subnational';
export type HistoricalPolity={
 id:string; name:string; era:PolityEra; start?:number; end?:number; region:string; aliases?:string[]; notes?:string;
};
/**
 * Historical-polity registry.
 * This is deliberately separate from the simulation state: a polity can exist in the
 * encyclopedia even when it is not selectable or active in a scenario.
 *
 * The registry is extensible and uses stable IDs so later era packs can add every
 * attested polity without changing save-game IDs.
 */
const rows:Array<[string,string,PolityEra,number,number,string,string[]]>=[
['akkad','Akkadian Empire','ancient',-2334,-2154,'Mesopotamia',[]],['sumer','Sumer','ancient',-4500,-1900,'Mesopotamia',[]],['ur-third-dynasty','Third Dynasty of Ur','ancient',-2112,-2004,'Mesopotamia',[]],
['old-babylonian','Old Babylonian Empire','ancient',-1894,-1595,'Mesopotamia',[]],['assyrian-empire','Assyrian Empire','ancient',-2500,-609,'Mesopotamia',[]],['neo-babylonian','Neo-Babylonian Empire','ancient',-626,-539,'Mesopotamia',[]],
['achaemenid','Achaemenid Empire','ancient',-550,-330,'Persia',[]],['seleucid','Seleucid Empire','ancient',-312,-63,'Middle East',[]],['parthian','Parthian Empire','ancient',-247,224,'Persia',[]],['sasanian','Sasanian Empire','ancient',224,651,'Persia',[]],
['ptolemaic','Ptolemaic Kingdom','ancient',-305,-30,'Egypt',[]],['macedon','Kingdom of Macedon','ancient',-808,-168,'Balkans',[]],['roman-republic','Roman Republic','ancient',-509,-27,'Mediterranean',[]],['roman-empire','Roman Empire','ancient',-27,395,'Mediterranean',[]],['western-roman','Western Roman Empire','ancient',395,476,'Europe',[]],['eastern-roman','Eastern Roman Empire','medieval',395,1453,'Eastern Mediterranean',['Byzantine Empire']],['gaul','Gaul','ancient',-50,486,'Western Europe',[]],['carthage','Carthaginian Empire','ancient',-814,-146,'North Africa',[]],['kingdom-of-kush','Kingdom of Kush','ancient',-1070,350,'Nile Valley',[]],
['aksum','Kingdom of Aksum','ancient',100,940,'Horn of Africa',[]],['ghaznavid','Ghaznavid Empire','medieval',977,1186,'Central Asia',[]],['seljuk','Great Seljuk Empire','medieval',1037,1194,'Middle East',[]],['khwarazmian','Khwarazmian Empire','medieval',1077,1231,'Central Asia',[]],['il-khanate','Ilkhanate','medieval',1256,1335,'Persia',[]],['timurid','Timurid Empire','medieval',1370,1507,'Central Asia',[]],
['mongol','Mongol Empire','medieval',1206,1368,'Eurasia',[]],['golden-horde','Golden Horde','medieval',1242,1502,'Eastern Europe',[]],['chagatai','Chagatai Khanate','medieval',1225,1347,'Central Asia',[]],['kiev-rus','Kievan Rus','medieval',882,1240,'Eastern Europe',[]],['novgorod','Novgorod Republic','medieval',1136,1478,'Eastern Europe',[]],['grand-principality-moscow','Grand Duchy of Moscow','medieval',1283,1547,'Eastern Europe',[]],
['holy-roman-empire','Holy Roman Empire','medieval',962,1806,'Central Europe',[]],['france-kingdom','Kingdom of France','medieval',987,1792,'Western Europe',[]],['england-kingdom','Kingdom of England','medieval',927,1707,'British Isles',[]],['scotland-kingdom','Kingdom of Scotland','medieval',843,1707,'British Isles',[]],
['castile','Crown of Castile','medieval',1065,1715,'Iberia',[]],['aragon','Crown of Aragon','medieval',1164,1716,'Iberia',[]],['portugal-kingdom','Kingdom of Portugal','medieval',1139,1910,'Iberia',[]],
['ottoman','Ottoman Empire','early-modern',1299,1922,'Anatolia',[]],['safavid','Safavid Iran','early-modern',1501,1736,'Persia',[]],['mughal','Mughal Empire','early-modern',1526,1857,'South Asia',[]],['maratha','Maratha Confederacy','early-modern',1674,1818,'South Asia',[]],
['qing','Qing Empire','early-modern',1636,1912,'East Asia',[]],['ming','Ming dynasty','early-modern',1368,1644,'East Asia',[]],['yuan','Yuan dynasty','medieval',1271,1368,'East Asia',[]],['lialiao','Liao dynasty','medieval',916,1125,'East Asia',[]],['jurchen-jin','Jin dynasty','medieval',1115,1234,'East Asia',[]],
['joseon','Joseon','early-modern',1392,1897,'Korea',[]],['korean-empire','Korean Empire','modern',1897,1910,'Korea',[]],['tokugawa','Tokugawa shogunate','early-modern',1603,1868,'Japan',[]],['meiji-japan','Empire of Japan','modern',1868,1947,'Japan',[]],
['aztec','Aztec Empire','early-modern',1428,1521,'Mesoamerica',[]],['inca','Inca Empire','early-modern',1438,1533,'Andes',[]],['maya','Maya civilization','ancient',-2000,1697,'Mesoamerica',[]],['toltec','Toltec civilization','ancient',900,1150,'Mesoamerica',[]],
['mali','Mali Empire','medieval',1235,1645,'West Africa',[]],['songhai','Songhai Empire','medieval',1464,1591,'West Africa',[]],['ghana-empire','Ghana Empire','medieval',300,1200,'West Africa',[]],['kanem-bornu','Kanem-Bornu Empire','medieval',700,1893,'Central Africa',[]],['ethiopian-empire','Ethiopian Empire','medieval',1270,1974,'Horn of Africa',[]],
['benin-kingdom','Kingdom of Benin','medieval',1180,1897,'West Africa',[]],['ashanti','Ashanti Empire','early-modern',1701,1957,'West Africa',[]],['kongo','Kingdom of Kongo','early-modern',1390,1914,'Central Africa',[]],
['great-zimbabwe','Kingdom of Zimbabwe','medieval',1100,1450,'Southern Africa',[]],['mutapa','Kingdom of Mutapa','early-modern',1430,1760,'Southern Africa',[]],
['swahili-city-states','Swahili city-states','medieval',700,1700,'East Africa',[]],['kilwa','Kilwa Sultanate','medieval',957,1513,'East Africa',[]],
['khmer-empire','Khmer Empire','medieval',802,1431,'Southeast Asia',[]],['srivijaya','Srivijaya','medieval',650,1377,'Southeast Asia',[]],['majapahit','Majapahit Empire','medieval',1293,1527,'Southeast Asia',[]],['pagan-kingdom','Pagan Kingdom','medieval',849,1297,'Southeast Asia',[]],['ayutthaya','Ayutthaya Kingdom','early-modern',1351,1767,'Southeast Asia',[]],['dai-viet','Đại Việt','medieval',1054,1804,'Vietnam',[]],
['polish-lithuanian','Polish-Lithuanian Commonwealth','early-modern',1569,1795,'Eastern Europe',[]],['poland-second','Second Polish Republic','modern',1918,1939,'Eastern Europe',[]],['austro-hungarian','Austria-Hungary','modern',1867,1918,'Central Europe',[]],['austrian-empire','Austrian Empire','early-modern',1804,1867,'Central Europe',[]],['prussia','Kingdom of Prussia','early-modern',1701,1918,'Central Europe',[]],
['german-empire','German Empire','modern',1871,1918,'Central Europe',[]],['weimar','Weimar Republic','modern',1919,1933,'Central Europe',[]],['francois-first-empire','First French Empire','early-modern',1804,1815,'Western Europe',[]],['napoleonic-kingdom-italy','Napoleonic Kingdom of Italy','early-modern',1805,1814,'Italy',[]],
['spanish-empire','Spanish Empire','early-modern',1492,1976,'Iberia and Americas',[]],['portuguese-empire','Portuguese Empire','early-modern',1415,1999,'Global',[]],['dutch-empire','Dutch Empire','early-modern',1581,1975,'Global',[]],['british-empire','British Empire','early-modern',1583,1997,'Global',[]],['french-colonial-empire','French colonial empire','early-modern',1534,1980,'Global',[]],
['belgian-colonial-empire','Belgian colonial empire','modern',1885,1962,'Central Africa',[]],['italian-empire','Italian Empire','modern',1885,1943,'Africa',[]],['german-colonial-empire','German colonial empire','modern',1884,1919,'Global',[]],
['russian-empire','Russian Empire','early-modern',1721,1917,'Eurasia',[]],['soviet-union','Soviet Union','modern',1922,1991,'Eurasia',['USSR']],['russian-sfsr','Russian SFSR','modern',1917,1991,'Eurasia',[]],['yugoslavia-kingdom','Kingdom of Yugoslavia','modern',1918,1941,'Balkans',[]],['yugoslavia-socialist','Socialist Federal Republic of Yugoslavia','modern',1945,1992,'Balkans',[]],
['czechoslovakia-first','First Czechoslovak Republic','modern',1918,1938,'Central Europe',[]],['czechoslovakia-second','Second Czechoslovak Republic','modern',1938,1939,'Central Europe',[]],['czechoslovakia-socialist','Czechoslovak Socialist Republic','modern',1960,1990,'Central Europe',[]],
['ottoman-beylik','Ottoman Beylik','medieval',1299,1453,'Anatolia',[]],['kingdom-of-greece','Kingdom of Greece','modern',1832,1924,'Balkans',[]],['greek-republic','Second Hellenic Republic','modern',1924,1935,'Balkans',[]],
['mexican-empire','First Mexican Empire','modern',1821,1823,'Mesoamerica',[]],['second-mexican-empire','Second Mexican Empire','modern',1864,1867,'Mesoamerica',[]],['gran-colombia','Gran Colombia','modern',1819,1831,'South America',[]],['viceroyalty-new-spain','Viceroyalty of New Spain','early-modern',1535,1821,'Americas',[]],['viceroyalty-peru','Viceroyalty of Peru','early-modern',1542,1824,'South America',[]],['viceroyalty-rio-plata','Viceroyalty of the Río de la Plata','early-modern',1776,1814,'South America',[]],
['united-provinces-rio','United Provinces of the Río de la Plata','modern',1810,1831,'South America',[]],['empire-brazil','Empire of Brazil','modern',1822,1889,'South America',[]],['kingdom-hawaii','Kingdom of Hawaii','modern',1795,1893,'Pacific',[]],['australian-commonwealth','Commonwealth of Australia','modern',1901,9999,'Oceania',[]],
['manchu-state','Manchukuo','modern',1932,1945,'East Asia',[]],['republic-china','Republic of China','modern',1912,9999,'East Asia',[]],['korean-peoples-republic','Provisional People’s Committee of North Korea','modern',1946,1948,'Korea',[]],
['free-france','Free France','modern',1940,1944,'Europe',[]],['vichy-france','French State','modern',1940,1944,'Western Europe',['Vichy France']],['italian-social-republic','Italian Social Republic','modern',1943,1945,'Italy',['Salò Republic']],
['ukrainian-people-republic','Ukrainian People’s Republic','modern',1917,1921,'Eastern Europe',[]],['west-ukrainian','West Ukrainian People’s Republic','modern',1918,1919,'Eastern Europe',[]],['belarusian-democratic-republic','Belarusian Democratic Republic','modern',1918,1919,'Eastern Europe',[]],['georgian-democratic-republic','Democratic Republic of Georgia','modern',1918,1921,'Caucasus',[]],['armenia-first-republic','First Republic of Armenia','modern',1918,1920,'Caucasus',[]],['azerbaijan-democratic-republic','Azerbaijan Democratic Republic','modern',1918,1920,'Caucasus',[]],
['tannu-tuva','Tuvan People’s Republic','modern',1921,1944,'Central Asia',[]],['mongolian-peoples-republic','Mongolian People’s Republic','modern',1924,1992,'East Asia',[]],['east-turkestan-republic','East Turkestan Republic','modern',1933,1934,'Central Asia',[]],['second-east-turkestan','Second East Turkestan Republic','modern',1944,1949,'Central Asia',[]],
['arab-republic-egypt-syria','United Arab Republic','modern',1958,1971,'Middle East',[]],['united-arab-states','United Arab States','modern',1958,1961,'Middle East',[]],['united-arab-republic','United Arab Republic','modern',1958,1971,'Middle East',[]],
['rhodesia','Rhodesia','modern',1965,1979,'Southern Africa',['Rhodesian Front']],['katanga','State of Katanga','modern',1960,1963,'Central Africa',[]],['biafra','Republic of Biafra','modern',1967,1970,'West Africa',[]],['somaliland-1991','Republic of Somaliland','modern',1991,9999,'Horn of Africa',[]],
['transkei','Transkei','modern',1976,1994,'Southern Africa',[]],['bophuthatswana','Bophuthatswana','modern',1977,1994,'Southern Africa',[]],['venda','Venda','modern',1979,1994,'Southern Africa',[]],['ciskei','Ciskei','modern',1981,1994,'Southern Africa',[]]
];

/* Expanded cross-era registry: regional kingdoms, republics, colonial administrations,
 * revolutionary governments, confederations, and short-lived/de facto states. */
rows.push(
['elam','Elam','ancient',-2700,-539,'Iran',[]],['urartu','Kingdom of Urartu','ancient',-860,-590,'Caucasus',[]],['lydia','Kingdom of Lydia','ancient',-1200,-546,'Anatolia',[]],['phrygia','Phrygian Kingdom','ancient',-1200,-695,'Anatolia',[]],['cappadocia','Kingdom of Cappadocia','ancient',-331,-17,'Anatolia',[]],['pontus','Kingdom of Pontus','ancient',-281,-62,'Anatolia',[]],['bithynia','Kingdom of Bithynia','ancient',-297,-74,'Anatolia',[]],['pergamon','Kingdom of Pergamon','ancient',-282,-133,'Anatolia',[]],['nabatea','Nabataean Kingdom','ancient',-312,106,'Arabia',[]],['saba','Kingdom of Saba','ancient',-1200,275,'Arabia',[]],['himyar','Himyarite Kingdom','ancient',-110,525,'Arabia',[]],['aksum','Kingdom of Aksum','ancient',100,940,'Horn of Africa',[]],
['maurya','Maurya Empire','ancient',-322,-185,'South Asia',[]],['shunga','Shunga Empire','ancient',-185,-73,'South Asia',[]],['satavahana','Satavahana dynasty','ancient',-230,220,'South Asia',[]],['kushan','Kushan Empire','ancient',30,375,'Central Asia',[]],['gupta','Gupta Empire','ancient',320,550,'South Asia',[]],['pallava','Pallava Kingdom','ancient',275,897,'South Asia',[]],['chola-ancient','Early Chola Kingdom','ancient',-300,300,'South India',[]],
['qin','Qin dynasty','ancient',-221,-206,'China',[]],['han','Han dynasty','ancient',-206,220,'China',[]],['xin','Xin dynasty','ancient',9,23,'China',[]],['three-kingdoms','Three Kingdoms','ancient',220,280,'China',[]],['western-jin','Western Jin','ancient',266,316,'China',[]],['eastern-jin','Eastern Jin','ancient',317,420,'China',[]],['southern-northern-dynasties','Southern and Northern Dynasties','medieval',420,589,'China',[]],['sui','Sui dynasty','medieval',581,618,'China',[]],['tang','Tang dynasty','medieval',618,907,'China',[]],['five-dynasties','Five Dynasties and Ten Kingdoms','medieval',907,979,'China',[]],['song','Song dynasty','medieval',960,1279,'China',[]],['western-xia','Western Xia','medieval',1038,1227,'China',[]],['jurchen-jin','Jin dynasty','medieval',1115,1234,'China',[]],['yuan','Yuan dynasty','medieval',1271,1368,'China',[]],['ming','Ming dynasty','early-modern',1368,1644,'China',[]],['qing','Qing dynasty','early-modern',1636,1912,'China',[]],
['goguryeo','Goguryeo','ancient',-37,668,'Korea',[]],['baekje','Baekje','ancient',-18,660,'Korea',[]],['silla','Silla','ancient',-57,935,'Korea',[]],['goryeo','Goryeo','medieval',918,1392,'Korea',[]],['joseon','Joseon','early-modern',1392,1897,'Korea',[]],['korean-empire','Korean Empire','modern',1897,1910,'Korea',[]],
['yayoi','Yayoi polity complex','ancient',-300,300,'Japan',[]],['yamato','Yamato polity','ancient',250,710,'Japan',[]],['asuka','Asuka period polity','ancient',538,710,'Japan',[]],['nara','Nara-period Japan','medieval',710,794,'Japan',[]],['heian','Heian-period Japan','medieval',794,1185,'Japan',[]],['kamakura','Kamakura shogunate','medieval',1185,1333,'Japan',[]],['ashikaga','Ashikaga shogunate','medieval',1336,1573,'Japan',[]],['azuchi-momoyama','Azuchi–Momoyama polity','early-modern',1568,1600,'Japan',[]],['tokugawa','Tokugawa shogunate','early-modern',1600,1868,'Japan',[]],
['anglo-saxon-heptarchy','Anglo-Saxon Heptarchy','medieval',500,927,'Britain',[]],['wessex','Kingdom of Wessex','medieval',519,927,'Britain',[]],['mercia','Kingdom of Mercia','medieval',527,918,'Britain',[]],['northumbria','Kingdom of Northumbria','medieval',654,954,'Britain',[]],['kingdom-ireland','Lordship of Ireland','medieval',1171,1542,'Ireland',[]],['kingdom-scotland','Kingdom of Scotland','medieval',843,1707,'Scotland',[]],['kingdom-england','Kingdom of England','medieval',927,1707,'England',[]],['great-britain','Kingdom of Great Britain','early-modern',1707,1801,'Britain',[]],['united-kingdom','United Kingdom of Great Britain and Ireland','modern',1801,1922,'Britain',[]],
['visigoths','Visigothic Kingdom','medieval',418,721,'Western Europe',[]],['ostrogoths','Ostrogothic Kingdom','medieval',493,553,'Italy',[]],['lombards','Kingdom of the Lombards','medieval',568,774,'Italy',[]],['franks','Frankish Kingdom','medieval',481,843,'Western Europe',[]],['merovingian','Merovingian Kingdom','medieval',450,751,'Western Europe',[]],['carolingian','Carolingian Empire','medieval',800,888,'Western Europe',[]],['west-francia','West Francia','medieval',843,987,'France',[]],['middle-francia','Middle Francia','medieval',843,855,'Western Europe',[]],['east-francia','East Francia','medieval',843,962,'Germany',[]],['burgundy-kingdom','Kingdom of Burgundy','medieval',411,1378,'Western Europe',[]],['kingdom-navarre','Kingdom of Navarre','medieval',824,1620,'Iberia',[]],['crown-aragon','Crown of Aragon','medieval',1164,1716,'Iberia',[]],['kingdom-castile','Kingdom of Castile','medieval',1065,1230,'Iberia',[]],['kingdom-leon','Kingdom of León','medieval',910,1230,'Iberia',[]],['kingdom-portugal','Kingdom of Portugal','medieval',1139,1910,'Portugal',[]],['granada','Emirate of Granada','medieval',1230,1492,'Iberia',[]],
['kyivan-rus','Kievan Rus','medieval',882,1240,'Eastern Europe',[]],['principality-vladimir','Grand Principality of Vladimir','medieval',1157,1389,'Eastern Europe',[]],['grand-duchy-lithuania','Grand Duchy of Lithuania','medieval',1236,1795,'Eastern Europe',[]],['teutonic-order-state','State of the Teutonic Order','medieval',1226,1525,'Baltic',[]],['livonian-confederation','Livonian Confederation','medieval',1228,1561,'Baltic',[]],['crimean-khanate','Crimean Khanate','medieval',1441,1783,'Black Sea',[]],['cossack-hetmanate','Cossack Hetmanate','early-modern',1648,1764,'Eastern Europe',[]],['polish-lithuanian','Polish–Lithuanian Commonwealth','early-modern',1569,1795,'Eastern Europe',[]],['free-city-krakow','Free City of Kraków','modern',1815,1846,'Central Europe',[]],
['prussia','Kingdom of Prussia','early-modern',1701,1918,'Central Europe',[]],['austrian-empire','Austrian Empire','early-modern',1804,1867,'Central Europe',[]],['austria-hungary','Austria-Hungary','modern',1867,1918,'Central Europe',[]],['german-confederation','German Confederation','modern',1815,1866,'Central Europe',[]],['german-empire','German Empire','modern',1871,1918,'Central Europe',[]],['weimar-republic','Weimar Republic','modern',1919,1933,'Germany',[]],['free-city-danzig','Free City of Danzig','modern',1920,1939,'Baltic',[]],['republic-of-ruthenia','Carpatho-Ukraine','modern',1939,1939,'Central Europe',[]],
['first-french-republic','First French Republic','modern',1792,1804,'France',[]],['first-empire','First French Empire','early-modern',1804,1815,'France',[]],['restoration-france','Bourbon Restoration','early-modern',1814,1830,'France',[]],['july-monarchy','July Monarchy','modern',1830,1848,'France',[]],['second-republic-france','Second French Republic','modern',1848,1852,'France',[]],['second-empire-france','Second French Empire','modern',1852,1870,'France',[]],['third-republic-france','French Third Republic','modern',1870,1940,'France',[]],['fourth-republic-france','French Fourth Republic','modern',1946,1958,'France',[]],
['kingdom-italy','Kingdom of Italy','modern',1861,1946,'Italy',[]],['papal-states','Papal States','medieval',756,1870,'Italy',[]],['republic-venice','Republic of Venice','medieval',697,1797,'Italy',[]],['republic-genoa','Republic of Genoa','medieval',1005,1797,'Italy',[]],['kingdom-two-sicilies','Kingdom of the Two Sicilies','modern',1816,1861,'Italy',[]],
['ottoman','Ottoman Empire','early-modern',1299,1922,'Middle East',[]],['mamluk-sultanate','Mamluk Sultanate','medieval',1250,1517,'Middle East',[]],['ayyubid-sultanate','Ayyubid Sultanate','medieval',1171,1260,'Middle East',[]],['seljuk-rum','Sultanate of Rum','medieval',1077,1308,'Anatolia',[]],['latin-empire','Latin Empire','medieval',1204,1261,'Balkans',[]],['empire-nicaea','Empire of Nicaea','medieval',1204,1261,'Anatolia',[]],['empire-trebizond','Empire of Trebizond','medieval',1204,1461,'Black Sea',[]],['byzantine','Byzantine Empire','medieval',330,1453,'Eastern Mediterranean',['Eastern Roman Empire']],['empire-trebizond','Empire of Trebizond','medieval',1204,1461,'Black Sea',[]],
['safavid','Safavid Iran','early-modern',1501,1736,'Iran',[]],['afsharid','Afsharid Iran','early-modern',1736,1796,'Iran',[]],['zand','Zand dynasty','early-modern',1751,1794,'Iran',[]],['qajar','Qajar Iran','early-modern',1789,1925,'Iran',[]],['pahlavi','Pahlavi Iran','modern',1925,1979,'Iran',[]],['durrani','Durrani Empire','early-modern',1747,1823,'Afghanistan',[]],['barakzai','Emirate of Afghanistan','modern',1823,1926,'Afghanistan',[]],
['ghaznavid','Ghaznavid Empire','medieval',977,1186,'Central Asia',[]],['ghurid','Ghurid Empire','medieval',879,1215,'Central Asia',[]],['khwarazmian','Khwarazmian Empire','medieval',1077,1231,'Central Asia',[]],['timurid','Timurid Empire','medieval',1370,1507,'Central Asia',[]],['shaybanid','Shaybanid Khanate','early-modern',1500,1599,'Central Asia',[]],['kokand','Khanate of Kokand','early-modern',1709,1876,'Central Asia',[]],['khiva','Khanate of Khiva','early-modern',1511,1920,'Central Asia',[]],['bukhara','Emirate of Bukhara','early-modern',1785,1920,'Central Asia',[]],
['ghana-empire','Ghana Empire','medieval',300,1200,'West Africa',[]],['mali-empire','Mali Empire','medieval',1235,1645,'West Africa',[]],['songhai','Songhai Empire','medieval',1430,1591,'West Africa',[]],['kanem-bornu','Kanem–Bornu Empire','medieval',700,1900,'Central Africa',[]],['sokoto','Sokoto Caliphate','early-modern',1804,1903,'West Africa',[]],['dahomey','Kingdom of Dahomey','early-modern',1600,1894,'West Africa',[]],['oyo','Oyo Empire','early-modern',1300,1896,'West Africa',[]],['ashanti','Ashanti Empire','early-modern',1670,1957,'West Africa',[]],['benin','Kingdom of Benin','medieval',1180,1897,'West Africa',[]],['kongo','Kingdom of Kongo','early-modern',1390,1914,'Central Africa',[]],['lunda','Lunda Kingdom','early-modern',1600,1887,'Central Africa',[]],['loango','Kingdom of Loango','early-modern',1600,1883,'Central Africa',[]],['ethiopian-empire','Ethiopian Empire','medieval',1270,1974,'Horn of Africa',[]],['zulu','Zulu Kingdom','modern',1816,1897,'Southern Africa',[]],['matabele','Ndebele Kingdom','modern',1820,1896,'Southern Africa',[]],['mutapa','Kingdom of Mutapa','medieval',1430,1760,'Southern Africa',[]],['great-zimbabwe','Kingdom of Zimbabwe','medieval',1100,1450,'Southern Africa',[]],
['carolingian-empire','Carolingian Empire','medieval',800,888,'Western Europe',[]],['holy-roman','Holy Roman Empire','medieval',962,1806,'Central Europe',[]],['hanseatic-league','Hanseatic League','medieval',1159,1669,'Northern Europe',[]],['kalmar-union','Kalmar Union','medieval',1397,1523,'Scandinavia',[]],['denmark-norway','Denmark–Norway','early-modern',1536,1814,'Scandinavia',[]],['sweden-finland','Kingdom of Sweden with Finland','early-modern',1523,1809,'Scandinavia',[]],['russian-tsardom','Tsardom of Russia','early-modern',1547,1721,'Russia',[]],['russian-empire','Russian Empire','early-modern',1721,1917,'Russia',[]],['provisional-government-russia','Russian Provisional Government','modern',1917,1917,'Russia',[]],['russian-sfsr','Russian SFSR','modern',1917,1991,'Russia',[]],
['new-granada','Republic of New Granada','modern',1831,1858,'South America',[]],['granadine-confederation','Granadine Confederation','modern',1858,1863,'South America',[]],['united-states-colombia','United States of Colombia','modern',1863,1886,'South America',[]],['viceroyalty-new-granada','Viceroyalty of New Granada','early-modern',1717,1819,'South America',[]],['captaincy-general-venezuela','Captaincy General of Venezuela','early-modern',1777,1821,'South America',[]],['captaincy-general-guatemala','Captaincy General of Guatemala','early-modern',1609,1821,'Central America',[]],['viceroyalty-new-spain','Viceroyalty of New Spain','early-modern',1535,1821,'North America',[]],['first-mexican-empire','First Mexican Empire','modern',1821,1823,'North America',[]],['second-mexican-empire','Second Mexican Empire','modern',1864,1867,'North America',[]],['central-america-federation','Federal Republic of Central America','modern',1823,1841,'Central America',[]],['haitian-empire','First Empire of Haiti','modern',1804,1806,'Caribbean',[]],['haitian-kingdom','Kingdom of Haiti','modern',1811,1820,'Caribbean',[]],['dominican-restoration','Second Dominican Republic founding','modern',1865,1865,'Caribbean',[]],['confederate-states','Confederate States of America','modern',1861,1865,'North America',[]],
['inca','Inca Empire','medieval',1438,1533,'Andes',[]],['aztec','Aztec Empire','medieval',1428,1521,'Mesoamerica',[]],['tarascan','Tarascan State','medieval',1300,1530,'Mesoamerica',[]],['maya-classic','Classic Maya polities','ancient',250,900,'Mesoamerica',[]],['toltec','Toltec state','medieval',900,1150,'Mesoamerica',[]],['teotihuacan','Teotihuacan polity','ancient',100,550,'Mesoamerica',[]],['mapuche-polities','Mapuche polities','early-modern',1500,1883,'Southern South America',[]],['tawantinsuyu','Tawantinsuyu','medieval',1438,1533,'Andes',['Inca Empire']],['gran-colombia','Gran Colombia','modern',1819,1831,'South America',[]],
['srivijaya','Srivijaya','medieval',650,1377,'Southeast Asia',[]],['maharajahit','Majapahit','medieval',1293,1527,'Southeast Asia',[]],['khmer-empire','Khmer Empire','medieval',802,1431,'Southeast Asia',[]],['pagan-kingdom','Pagan Kingdom','medieval',849,1297,'Myanmar',[]],['ayutthaya','Ayutthaya Kingdom','early-modern',1351,1767,'Thailand',[]],['lan-xang','Lan Xang','early-modern',1353,1707,'Laos',[]],['dai-viet','Đại Việt','medieval',1054,1804,'Vietnam',[]],['nguyen-vietnam','Nguyễn dynasty Vietnam','early-modern',1802,1945,'Vietnam',[]],['brunei-sultanate','Brunei Sultanate','early-modern',1368,9999,'Borneo',[]],['sulu-sultanate','Sulu Sultanate','early-modern',1450,1915,'Philippines',[]],
['mughal','Mughal Empire','early-modern',1526,1857,'South Asia',[]],['maratha','Maratha Confederacy','early-modern',1674,1818,'South Asia',[]],['sikh-empire','Sikh Empire','early-modern',1799,1849,'South Asia',[]],['hyderabad','Hyderabad State','modern',1724,1948,'South Asia',[]],['mysore','Kingdom of Mysore','early-modern',1399,1947,'South Asia',[]],['awadh','Kingdom of Awadh','early-modern',1722,1858,'South Asia',[]],
['kingdom-egypt','Kingdom of Egypt','modern',1922,1953,'Egypt',[]],['sultanate-egypt','Sultanate of Egypt','early-modern',1914,1922,'Egypt',[]],['libya-kingdom','Kingdom of Libya','modern',1951,1969,'North Africa',[]],['tunisian-regency','Beylik of Tunis','early-modern',1574,1881,'North Africa',[]],['algerian-regency','Regency of Algiers','early-modern',1516,1830,'North Africa',[]],['morocco-sultanate','Sultanate of Morocco','early-modern',1660,1957,'North Africa',[]],
['mandate-palestine','Mandate for Palestine','modern',1920,1948,'Levant',[]],['transjordan-emirate','Emirate of Transjordan','modern',1921,1946,'Levant',[]],['lebanon-state','State of Greater Lebanon','modern',1920,1943,'Levant',[]],['syrian-kingdom','Arab Kingdom of Syria','modern',1920,1920,'Levant',[]],['kingdom-iraq','Kingdom of Iraq','modern',1921,1958,'Mesopotamia',[]],
['first-republic-china','Republic of China government','modern',1912,1949,'East Asia',[]],['warlord-era-china','Chinese warlord governments','modern',1916,1928,'China',[]],['provisional-republic-korea','Provisional Government of the Republic of Korea','modern',1919,1948,'Korea',[]],['empire-korea','Korean Empire','modern',1897,1910,'Korea',[]],
['westphalian-netherlands','Dutch Republic','early-modern',1581,1795,'Netherlands',[]],['batavian-republic','Batavian Republic','early-modern',1795,1806,'Netherlands',[]],['kingdom-holland','Kingdom of Holland','early-modern',1806,1810,'Netherlands',[]],['first-portuguese-republic','First Portuguese Republic','modern',1910,1926,'Portugal',[]],['portuguese-first-empire','Portuguese Empire','early-modern',1415,1999,'Global',[]],['spanish-empire','Spanish Empire','early-modern',1492,1976,'Global',[]],['dutch-empire','Dutch colonial empire','early-modern',1602,1975,'Global',[]],['french-colonial-empire','French colonial empire','early-modern',1534,1980,'Global',[]],['british-empire','British Empire','early-modern',1583,1997,'Global',[]],
['belgian-colonial-empire','Belgian colonial empire','modern',1885,1962,'Africa',[]],['german-colonial-empire','German colonial empire','modern',1884,1919,'Global',[]],['italian-colonial-empire','Italian colonial empire','modern',1890,1943,'Africa',[]],['japanese-empire','Empire of Japan','modern',1868,1947,'East Asia',[]]
);

export const historicalPolities:Record<string,HistoricalPolity>=Object.fromEntries(rows.map(([id,name,era,start,end,region,aliases])=>[id,{id,name,era,start,end,region,aliases}]));
export function searchHistoricalPolities(query:string){const q=query.toLowerCase().trim();return Object.values(historicalPolities).filter(p=>p.name.toLowerCase().includes(q)||(p.aliases??[]).some(a=>a.toLowerCase().includes(q)));}
export function politiesAtYear(year:number){return Object.values(historicalPolities).filter(p=>(p.start??-99999)<=year&&(p.end??99999)>=year);}
