export type HistoricalRecordKind='event'|'place'|'person';
export type HistoricalRecord={
 id:string; kind:HistoricalRecordKind; name:string; start?:number; end?:number;
 date?:string; region:string; description:string; tags:string[];
 relatedPolities?:string[]; location?:{lat:number;lon:number};
 significance?:number; source:string; confidence:'high'|'medium';
};
/**
 * Worldforge Historical Record Pack v1.
 * Curated, normalized records intended for simulation context, encyclopedia search,
 * event generation and place/person lookup. Dates use astronomical year numbering
 * where practical (negative = BCE); exact ancient dates are intentionally avoided.
 */
const E=(id:string,name:string,start:number,region:string,description:string,tags:string[],polities:string[]=[],significance=5):HistoricalRecord=>({id,kind:'event',name,start,region,description,tags,relatedPolities:polities,significance,source:'Worldforge curated historical pack',confidence:'high'});
const P=(id:string,name:string,start:number,region:string,description:string,tags:string[],lat:number,lon:number,polities:string[]=[],significance=5):HistoricalRecord=>({id,kind:'place',name,start,region,description,tags,location:{lat,lon},relatedPolities:polities,significance,source:'Worldforge curated historical pack',confidence:'high'});
const H=(id:string,name:number|string,start:number,end:number|undefined,region:string,description:string,tags:string[],polities:string[]=[],significance=5):HistoricalRecord=>({id,kind:'person',name:String(name),start,end,region,description,tags,relatedPolities:polities,significance,source:'Worldforge curated historical pack',confidence:'high'});

export const historicalRecords:HistoricalRecord[]=[
E('sumer-urbanization','Rise of Sumerian city-states',-3500,'Mesopotamia','Growth of urban centers, writing and organized institutions in southern Mesopotamia.',['ancient','urban','writing'],['sumer'],8),
E('akkad-conquest','Akkadian imperial expansion',-2334,'Mesopotamia','Sargon of Akkad built an early territorial empire across Mesopotamia.',['war','empire','mesopotamia'],['akkad'],8),
E('ur-iii','Third Dynasty of Ur established',-2112,'Mesopotamia','Ur became the center of a highly administered Mesopotamian state.',['state','administration','bronze-age'],['ur-third-dynasty'],6),
E('hammurabi-reign','Hammurabi consolidates Babylonia',-1792,'Mesopotamia','Babylon expanded under Hammurabi and became a major Mesopotamian power.',['war','law','babylon'],['old-babylonian'],8),
E('hittite-babylon','Hittite sack of Babylon',-1595,'Mesopotamia','A Hittite campaign ended the Old Babylonian dynasty.',['war','collapse'],['old-babylonian'],6),
E('sea-peoples','Late Bronze Age disruptions',-1200,'Eastern Mediterranean','A period of warfare, migration and political disruption affected several eastern Mediterranean states.',['bronze-age','migration','collapse'],[],9),
E('neo-assyrian-expansion','Neo-Assyrian imperial expansion',-900,'Near East','Assyria developed a large militarized empire across the Near East.',['empire','war','assyria'],['assyrian-empire'],8),
E('babylon-fall','Fall of Babylon to Cyrus',-539,'Mesopotamia','The Achaemenid conquest incorporated Babylon into the Persian Empire.',['conquest','persia'],['neo-babylonian','achaemenid'],8),
E('marathon','Battle of Marathon',-490,'Greece','Athenian forces defeated a Persian expeditionary force near Marathon.',['battle','persian-wars'],['achaemenid'],8),
E('thermopylae','Battle of Thermopylae',-480,'Greece','A Persian invasion force fought Greek defenders at Thermopylae.',['battle','persian-wars'],['achaemenid'],7),
E('salamis','Battle of Salamis',-480,'Greece','Greek naval forces defeated the Persian fleet near Salamis.',['naval','battle','persian-wars'],['achaemenid'],9),
E('alexander-conquest','Alexanderian conquest of Persia',-334,'Mediterranean and Asia','Macedonian armies conquered the Achaemenid Empire and reached deep into Asia.',['conquest','hellenistic'],['macedon','achaemenid'],9),
E('cannae','Battle of Cannae',-216,'Italy','Hannibal won a major tactical victory over Rome during the Second Punic War.',['battle','rome','carthage'],['carthage','roman-republic'],9),
E('carthage-destruction','Destruction of Carthage',-146,'North Africa','Rome destroyed Carthage at the end of the Third Punic War.',['war','rome','carthage'],['carthage','roman-republic'],8),
E('roman-caesar','Caesar crosses the Rubicon',-49,'Italy','Julius Caesar crossed into Italy with his army, beginning a civil war.',['civil-war','rome'],['roman-republic'],9),
E('actium','Battle of Actium',-31,'Mediterranean','Octavian defeated the forces of Antony and Cleopatra in a decisive naval engagement.',['naval','civil-war','rome'],['roman-republic'],9),
E('augustus','Augustus becomes first Roman emperor',-27,'Rome','Octavian established the political order conventionally associated with the Roman Empire.',['rome','imperial'],['roman-empire'],9),
E('pompeii','Vesuvius eruption and destruction of Pompeii',79,'Italy','Mount Vesuvius erupted and buried Pompeii and neighboring settlements.',['disaster','volcano','archaeology'],[],8),
E('constantine','Constantine wins at Milvian Bridge',312,'Italy','Constantine defeated Maxentius and secured control of the western Roman Empire.',['battle','rome','religion'],['roman-empire'],8),
E('edict-milan','Edict of Milan',313,'Roman Empire','Imperial policy granted toleration to Christianity and other religions.',['religion','law'],['roman-empire'],7),
E('theodosius','Roman Empire permanently divided',395,'Mediterranean','After Theodosius I, eastern and western imperial administrations developed separately.',['rome','politics'],['western-roman','eastern-roman'],8),
E('western-fall','Fall of the Western Roman Empire',476,'Western Europe','The deposition of Romulus Augustulus conventionally marks the end of the Western Roman Empire.',['collapse','rome'],['western-roman'],10),
E('justinian-reconquest','Justinianian reconquests',533,'Mediterranean','Eastern Roman armies reconquered parts of North Africa and Italy.',['war','byzantium'],['eastern-roman'],7),
E('hegira','Hijra of Muhammad to Medina',622,'Arabia','Muhammad migrated from Mecca to Medina, an event central to the Islamic calendar.',['religion','migration'],[],10),
E('arab-conquests','Early Islamic conquests',630,'Middle East','Arab-Muslim armies rapidly expanded across the Middle East, North Africa and beyond.',['conquest','caliphate'],[],10),
E('tang-foundation','Tang dynasty established',618,'China','The Tang dynasty reunified much of China and oversaw a major period of expansion.',['china','dynasty'],['tang'],8),
E('tang-an-lushan','An Lushan Rebellion',755,'China','A devastating rebellion severely weakened the Tang state.',['rebellion','china','civil-war'],['tang'],9),
E('norman-conquest','Norman Conquest of England',1066,'England','William of Normandy defeated Harold II and established Norman rule in England.',['conquest','england'],['england-kingdom'],10),
E('first-crusade','First Crusade',1096,'Levant','Western European crusading armies campaigned in the eastern Mediterranean.',['crusade','war'],[],9),
E('magna-carta','Magna Carta',1215,'England','English barons compelled King John to accept a charter limiting aspects of royal authority.',['law','constitution','england'],['england-kingdom'],9),
E('mongol-invasion','Mongol conquest begins in North China',1211,'East Asia','Mongol forces expanded into the Jin and wider East Asian political system.',['mongol','conquest'],['mongol'],8),
E('baghdad-fall','Mongol capture of Baghdad',1258,'Mesopotamia','Hülegü’s forces captured Baghdad, ending Abbasid political authority there.',['conquest','mongol','baghdad'],['mongol','il-khanate'],10),
E('black-death','Black Death reaches Europe',1347,'Europe','Plague spread through Europe and caused catastrophic mortality and social disruption.',['plague','demography','disaster'],[],10),
E('constantinople-fall','Fall of Constantinople',1453,'Constantinople','Ottoman forces captured Constantinople, ending the Byzantine Empire.',['conquest','ottoman','byzantium'],['ottoman','eastern-roman'],10),
E('columbus-voyage','Columbus reaches the Americas',1492,'Atlantic','Christopher Columbus reached Caribbean islands during a voyage sponsored by Castile.',['exploration','atlantic','colonialism'],['castile'],10),
E('tordesillas','Treaty of Tordesillas',1494,'Atlantic','Castile and Portugal agreed to a division of overseas spheres of expansion.',['treaty','colonialism'],['spanish-empire','portuguese-empire'],8),
E('reformation','Lutheran Reformation begins',1517,'Central Europe','Martin Luther’s challenge to church practices helped initiate the Protestant Reformation.',['religion','reformation'],[],10),
E('tenochtitlan','Fall of Tenochtitlan',1521,'Mesoamerica','Spanish and Indigenous allies defeated the Mexica state and captured its capital.',['conquest','mesoamerica'],['aztec'],10),
E('magellan','Magellan expedition begins',1519,'Atlantic and Pacific','The expedition associated with Ferdinand Magellan began the first circumnavigation of Earth.',['exploration','navigation'],[],8),
E('lepanto','Battle of Lepanto',1571,'Mediterranean','The Holy League defeated an Ottoman fleet in a major Mediterranean naval battle.',['naval','ottoman'],['ottoman'],8),
E('defenestration','Defenestration of Prague',1618,'Bohemia','The Prague defenestration helped trigger the Bohemian Revolt and Thirty Years’ War.',['rebellion','central-europe','war'],[],9),
E('westphalia','Peace of Westphalia',1648,'Europe','Treaties ending major parts of the Thirty Years’ War reshaped European diplomacy.',['treaty','diplomacy','war'],[],10),
E('glorious-revolution','Glorious Revolution',1688,'Britain','James II was displaced and William and Mary took the English throne.',['revolution','monarchy'],['england-kingdom'],9),
E('american-independence','American Declaration of Independence',1776,'North America','Thirteen British colonies declared independence and formed a revolutionary state.',['revolution','independence'],[],10),
E('french-revolution','French Revolution begins',1789,'France','The French Revolution transformed the political and social order of France and Europe.',['revolution','politics'],['first-french-republic'],10),
E('bastille','Storming of the Bastille',1789,'Paris','Revolutionaries seized the Bastille during the early French Revolution.',['revolution','paris'],['first-french-republic'],8),
E('haitian-revolution','Haitian Revolution begins',1791,'Caribbean','Enslaved and free people launched a revolution that ultimately produced Haitian independence.',['revolution','abolition','independence'],[],10),
E('napoleon-coup','Napoleon’s coup of 18 Brumaire',1799,'France','Napoleon Bonaparte helped overthrow the Directory and establish the Consulate.',['coup','france'],['first-french-republic'],9),
E('trafalgar','Battle of Trafalgar',1805,'Atlantic','British naval forces defeated a combined French-Spanish fleet.',['naval','napoleonic-wars'],['first-empire'],9),
E('waterloo','Battle of Waterloo',1815,'Belgium','Coalition forces defeated Napoleon, ending his Hundred Days.',['battle','napoleonic-wars'],['first-empire'],10),
E('congress-vienna','Congress of Vienna',1814,'Europe','European powers negotiated a post-Napoleonic settlement and balance of power.',['diplomacy','europe'],[],9),
E('greek-independence','Greek War of Independence begins',1821,'Greece','Greek revolutionaries began a successful struggle against Ottoman rule.',['revolution','independence'],['ottoman'],8),
E('indian-rebellion','Indian Rebellion of 1857',1857,'South Asia','A major uprising challenged East India Company rule and led to direct British Crown administration.',['rebellion','colonialism'],[],10),
E('italy-unification','Kingdom of Italy proclaimed',1861,'Italy','The Kingdom of Italy was proclaimed during the process of Italian unification.',['unification','nationalism'],['kingdom-italy'],9),
E('american-civil-war','American Civil War begins',1861,'North America','The United States entered a civil war following secession and conflict over the Union and slavery.',['civil-war','slavery'],['confederate-states'],10),
E('emancipation','Emancipation Proclamation',1863,'North America','The U.S. proclamation declared enslaved people in rebelling areas to be free as a wartime measure.',['slavery','war','law'],[],9),
E('german-unification','German Empire proclaimed',1871,'Central Europe','The German Empire was proclaimed after Prussian-led unification wars.',['unification','nationalism'],['german-empire'],10),
E('scramble-africa','Berlin Conference',1884,'Africa','European powers negotiated rules for colonial claims in Africa.',['colonialism','diplomacy'],[],9),
E('meiji-restoration','Meiji Restoration',1868,'Japan','Political authority was reorganized around the emperor and Japan embarked on rapid institutional modernization.',['japan','modernization'],['meiji-japan'],9),
E('boxer-rebellion','Boxer Uprising',1899,'China','The anti-foreign and anti-Christian Boxer movement culminated in international military intervention.',['rebellion','china','imperialism'],['qing'],8),
E('russian-revolution-1905','Russian Revolution of 1905',1905,'Russia','Mass protest and political crisis forced concessions from the Russian imperial government.',['revolution','russia'],['russian-empire'],8),
E('wwi','First World War',1914,'Europe and world','A global war involving major alliances transformed borders, empires and societies.',['world-war','industrial-war'],['german-empire','austro-hungarian','russian-empire'],10),
E('russian-february','February Revolution',1917,'Russia','Mass unrest and military breakdown led to the abdication of Nicholas II.',['revolution','russia'],['russian-empire'],10),
E('russian-october','October Revolution',1917,'Russia','Bolshevik forces seized key government institutions in Petrograd.',['revolution','russia'],['russian-sfsr'],10),
E('versailles','Treaty of Versailles',1919,'Europe','The peace treaty imposed terms on Germany and helped establish the postwar settlement.',['treaty','wwi'],['german-empire'],10),
E('league','League of Nations established',1920,'International','The League of Nations began operating as an international organization after World War I.',['diplomacy','international'],[],8),
E('great-depression','Great Depression begins',1929,'Global','A worldwide economic crisis produced severe unemployment, deflation and political disruption.',['economy','crisis'],[],10),
E('manchuria','Japanese invasion of Manchuria',1931,'East Asia','Japanese forces seized Manchuria and established Manchukuo.',['war','imperialism'],['manchu-state'],9),
E('spanish-civil-war','Spanish Civil War begins',1936,'Spain','Military revolt developed into a major civil war involving foreign intervention.',['civil-war','ideology'],[],10),
E('munich','Munich Agreement',1938,'Central Europe','Britain, France, Germany and Italy agreed to the transfer of the Sudetenland from Czechoslovakia to Germany.',['diplomacy','central-europe'],['czechoslovakia-first'],10),
E('wwii','Second World War',1939,'Global','A global war transformed political borders, economies and societies across multiple continents.',['world-war','total-war'],[],10),
E('barbarossa','Operation Barbarossa',1941,'Eastern Europe','Germany launched its invasion of the Soviet Union.',['war','eastern-front'],['soviet-union'],10),
E('pearl-harbor','Attack on Pearl Harbor',1941,'Pacific','Japanese forces attacked the U.S. Pacific Fleet base, bringing the United States into the Pacific War.',['war','naval'],[],10),
E('stalingrad','Battle of Stalingrad',1942,'Eastern Europe','The prolonged battle ended with the surrender of the German Sixth Army and became a major turning point on the Eastern Front.',['battle','wwii'],['soviet-union'],10),
E('normandy','Normandy landings',1944,'France','Allied forces established a major western European beachhead in Normandy.',['invasion','wwii'],[],10),
E('hiroshima','Atomic bombing of Hiroshima',1945,'Japan','The United States used an atomic bomb against Hiroshima during the final phase of the Pacific War.',['nuclear','wwii'],[],10),
E('un-creation','United Nations founded',1945,'International','The United Nations was established as a new international organization after World War II.',['diplomacy','international'],[],10),
E('india-independence','Indian independence',1947,'South Asia','British rule in India ended and the subcontinent was partitioned into new states.',['independence','decolonization'],[],10),
E('nato','NATO established',1949,'North Atlantic','Twelve states signed the North Atlantic Treaty establishing a collective-defense organization.',['alliance','cold-war'],[],9),
E('chinese-revolution','People’s Republic of China proclaimed',1949,'China','The Chinese Communist Party established the People’s Republic of China after the civil war.',['revolution','china'],[],10),
E('korean-war','Korean War begins',1950,'Korea','War broke out on the Korean Peninsula and became an internationalized Cold War conflict.',['war','cold-war'],[],10),
E('suez','Suez Crisis',1956,'Middle East','The nationalization of the Suez Canal was followed by an Anglo-French-Israeli military intervention and international pressure for withdrawal.',['war','diplomacy','suez'],[],9),
E('cuban-revolution','Cuban Revolution triumph',1959,'Caribbean','Revolutionary forces overthrew the Batista government.',['revolution','cold-war'],[],9),
E('berlin-wall','Berlin Wall constructed',1961,'Germany','East German authorities began constructing the Berlin Wall around West Berlin.',['cold-war','border'],[],9),
E('cuban-missile','Cuban Missile Crisis',1962,'Caribbean','The United States and Soviet Union confronted each other over Soviet missiles in Cuba.',['nuclear','cold-war','diplomacy'],['soviet-union'],10),
E('moon-landing','Apollo 11 Moon landing',1969,'Moon','Humans landed on the Moon during the Apollo 11 mission.',['space','technology'],[],9),
E('bangladesh','Bangladesh independence war',1971,'South Asia','Conflict in East Pakistan culminated in the creation of Bangladesh.',['war','independence'],[],9),
E('oil-crisis','1973 oil crisis',1973,'Global','Oil supply restrictions and price increases produced a major global economic shock.',['economy','energy'],[],9),
E('vietnam-fall','Fall of Saigon',1975,'Vietnam','North Vietnamese forces captured Saigon, ending the Vietnam War.',['war','decolonization'],[],9),
E('iran-revolution','Iranian Revolution',1979,'Iran','A revolutionary movement overthrew the Pahlavi monarchy and established a new political order.',['revolution','iran'],['pahlavi'],10),
E('berlin-wall-fall','Fall of the Berlin Wall',1989,'Germany','East German border restrictions collapsed and the Berlin Wall ceased functioning as a closed border.',['cold-war','germany'],[],10),
E('soviet-dissolution','Dissolution of the Soviet Union',1991,'Eurasia','The Soviet Union ceased to exist and fifteen independent republics emerged.',['collapse','cold-war'],['soviet-union'],10),
E('yugoslavia-breakup','Breakup of Yugoslavia',1991,'Balkans','The Socialist Federal Republic of Yugoslavia entered a prolonged period of dissolution and armed conflict.',['collapse','war','balkans'],['yugoslavia-socialist'],10),
E('rwandan-genocide','Rwandan genocide',1994,'Great Lakes Africa','A genocide in Rwanda killed large numbers of Tutsi and moderate Hutu civilians.',['genocide','africa'],[],10),
E('euro-intro','Euro introduced as accounting currency',1999,'Europe','The euro became an accounting currency for participating states before notes and coins entered circulation in 2002.',['economy','europe'],[],7),
E('9-11','September 11 attacks',2001,'United States','Terrorist attacks in the United States prompted major changes in international security and warfare.',['terrorism','security'],[],10),
E('iraq-war','Iraq War begins',2003,'Iraq','A U.S.-led coalition invaded Iraq, overthrowing the Ba’athist government.',['war','middle-east'],[],9),
E('arab-spring','Arab Spring begins',2010,'North Africa and Middle East','Protests and uprisings spread across several Arab states and produced varied political outcomes.',['protest','revolution','middle-east'],[],9),
E('crimea-2014','Russian annexation of Crimea',2014,'Crimea','Russia took control of Crimea after the 2014 political crisis in Ukraine; the annexation was not recognized by Ukraine and many states.',['war','territory','ukraine'],['russian-empire'],10),
E('covid-pandemic','COVID-19 pandemic declared',2020,'Global','A global infectious disease pandemic produced widespread mortality, public-health measures and economic disruption.',['pandemic','economy','society'],[],10),

P('ur','Ur',-3000,'Mesopotamia','Major Sumerian urban center near the Euphrates and a center of early state formation.',['city','archaeology','sumer'],30.962,46.104,['sumer','ur-third-dynasty'],9),
P('babylon','Babylon',-1800,'Mesopotamia','Ancient city on the Euphrates and capital of several Babylonian states.',['city','mesopotamia'],32.542,44.421,['old-babylonian','neo-babylonian'],10),
P('nineveh','Nineveh',-900,'Mesopotamia','Ancient Assyrian capital on the Tigris near modern Mosul.',['city','assyria'],36.359,43.152,['assyrian-empire'],9),
P('persepolis','Persepolis',-515,'Persia','Ceremonial capital of the Achaemenid Empire.',['city','persia','archaeology'],29.935,52.891,['achaemenid'],9),
P('athens','Athens',-500,'Greece','Greek polis and major center of political, military and cultural development.',['city','greece'],37.984,23.728,['roman-republic'],9),
P('sparta','Sparta',-500,'Greece','Peloponnesian polis noted for its militarized social organization.',['city','greece'],37.074,22.43,[],8),
P('rome','Rome',-753,'Italy','Capital of the Roman state and a central Mediterranean political center.',['city','rome'],41.9028,12.4964,['roman-republic','roman-empire'],10),
P('carthage-place','Carthage',-814,'North Africa','Phoenician-founded city that became the center of a major Mediterranean power.',['city','carthage'],36.8528,10.3233,['carthage'],10),
P('alexandria','Alexandria',-331,'Egypt','Mediterranean port founded by Alexander and major Hellenistic intellectual center.',['city','egypt'],31.2,29.918,['ptolemaic'],9),
P('constantinople','Constantinople',330,'Bosphorus','Imperial capital founded as New Rome and later capital of the Byzantine Empire and Ottoman Empire.',['city','rome','byzantium','ottoman'],41.0082,28.9784,['eastern-roman','ottoman'],10),
P('baghdad','Baghdad',762,'Mesopotamia','Abbasid capital and major intellectual, commercial and political center.',['city','islamic-world'],33.3152,44.3661,[],10),
P('cordoba','Cordoba',929,'Iberia','Major city of al-Andalus and capital of the Caliphate of Córdoba.',['city','islamic-world','iberia'],37.8882,-4.7794,[],9),
P('timbuktu','Timbuktu',1300,'West Africa','Important trans-Saharan commercial and scholarly center.',['city','mali','trade'],16.7666,-3.0026,['mali'],9),
P('venice','Venice',1200,'Italy','Maritime republic and major Mediterranean commercial center.',['city','trade','republic'],45.44,12.315,['republic-venice'],9),
P('kyiv','Kyiv',1000,'Eastern Europe','Major East European center associated with Kyivan Rus and later states.',['city','eastern-europe'],50.4501,30.5234,['kiev-rus'],9),
P('cracow','Kraków',1000,'Central Europe','Major Polish political and cultural center.',['city','poland'],50.0647,19.945,['polish-lithuanian'],8),
P('prague','Prague',1000,'Central Europe','Bohemian and later Czech political center on the Vltava.',['city','bohemia','czechia'],50.0755,14.4378,['holy-roman-empire','czechoslovakia-first'],10),
P('constantinople-1453','Walls of Constantinople',1453,'Constantinople','Fortification system central to the defense and eventual Ottoman conquest of the city.',['fortification','siege'],41.0082,28.9784,['eastern-roman','ottoman'],9),
P('tenochtitlan-place','Tenochtitlan',1500,'Mesoamerica','Mexica imperial capital built on islands in Lake Texcoco.',['city','mexica','mesoamerica'],19.4326,-99.1332,['aztec'],10),
P('cusco','Cusco',1450,'Andes','Capital and ceremonial center of the Inca Empire.',['city','inca','andes'],-13.5319,-71.9675,['inca'],10),
P('istanbul','Istanbul',1500,'Anatolia','Ottoman imperial capital following the conquest of Constantinople.',['city','ottoman'],41.0082,28.9784,['ottoman'],10),
P('paris','Paris',1400,'France','Major French political and cultural center.',['city','france'],48.8566,2.3522,[],10),
P('london','London',1400,'England','Political and commercial center of England and later the United Kingdom.',['city','britain'],51.5074,-0.1278,['england-kingdom','united-kingdom'],10),
P('amsterdam','Amsterdam',1600,'Netherlands','Major Dutch commercial and financial center during the Dutch Golden Age.',['city','trade'],52.3676,4.9041,['dutch-empire'],8),
P('vienna','Vienna',1700,'Central Europe','Habsburg imperial capital and major Central European diplomatic center.',['city','habsburg'],48.2082,16.3738,['austrian-empire','austro-hungarian'],10),
P('berlin','Berlin',1700,'Germany','Prussian capital and later German imperial capital.',['city','prussia','germany'],52.52,13.405,['prussia','german-empire'],10),
P('washington','Washington, D.C.',1800,'North America','Capital of the United States and seat of its federal government.',['city','capital'],38.9072,-77.0369,[],10),
P('new-york','New York',1800,'North America','Major Atlantic port and commercial center of the United States.',['city','trade'],40.7128,-74.006,[],9),
P('sao-paulo','São Paulo',1900,'South America','Major industrial and commercial city in Brazil.',['city','industry'],-23.5558,-46.6396,['empire-brazil'],7),
P('tokyo','Tokyo',1600,'Japan','Japanese political center, first as Edo and later as Tokyo.',['city','japan'],35.6762,139.6503,['tokugawa','meiji-japan'],10),
P('delhi','Delhi',1200,'South Asia','Major South Asian imperial and political center.',['city','india'],28.6139,77.209,[],10),
P('beijing','Beijing',1400,'China','Chinese imperial capital under the Ming and Qing dynasties.',['city','china'],39.9042,116.4074,['ming','qing'],10),
P('moscow','Moscow',1400,'Russia','Russian political center that became capital of the Russian state and later USSR.',['city','russia'],55.7558,37.6173,['grand-principality-moscow','russian-empire','soviet-union'],10),
P('cairo','Cairo',1000,'Egypt','Major Nile city and political center of Egypt.',['city','egypt'],30.0444,31.2357,[],9),
P('jerusalem','Jerusalem',-1000,'Levant','Ancient and enduring religious and political center.',['city','religion'],31.7683,35.2137,[],10),
P('mecca','Mecca',600,'Arabia','Islamic holy city and birthplace of Muhammad.',['city','religion'],21.4225,39.8262,[],10),
P('medina','Medina',600,'Arabia','City where Muhammad established the early Muslim community after the Hijra.',['city','religion'],24.4672,39.6112,[],10),

H('sargon-akkad','Sargon of Akkad',-2334,-2279,'Mesopotamia','Founder of the Akkadian Empire and one of the earliest known imperial rulers.',['ruler','akkad'],['akkad'],9),
H('hammurabi','Hammurabi',-1792,-1750,'Mesopotamia','Babylonian king associated with imperial expansion and a famous law collection.',['ruler','law','babylon'],['old-babylonian'],9),
H('cyrus-great','Cyrus the Great',-559,-530,'Persia','Founder of the Achaemenid Empire and conqueror of Babylon.',['ruler','persia','empire'],['achaemenid'],10),
H('darius-great','Darius I',-522,-486,'Persia','Achaemenid ruler who consolidated the empire and sponsored major administrative works.',['ruler','persia'],['achaemenid'],9),
H('leonidas','Leonidas I',-490,-480,'Greece','Spartan king who commanded Greek defenders at Thermopylae.',['ruler','battle'],[],8),
H('alexander-great','Alexander the Great',-356,-323,'Macedon and Asia','Macedonian king whose conquests created a vast Hellenistic realm.',['ruler','conqueror'],['macedon'],10),
H('hannibal','Hannibal Barca',-247,-183,'Carthage','Carthaginian commander who invaded Italy during the Second Punic War.',['commander','war'],['carthage'],10),
H('julius-caesar','Julius Caesar',-100,-44,'Rome','Roman general and statesman whose civil war helped end the Roman Republic.',['ruler','commander','rome'],['roman-republic'],10),
H('augustus-person','Augustus',-63,14,'Rome','First Roman emperor and architect of the early imperial settlement.',['ruler','rome'],['roman-empire'],10),
H('constantine-person','Constantine the Great',272,337,'Roman Empire','Roman emperor who reunited the empire and supported Christianity.',['ruler','religion'],['roman-empire'],9),
H('justinian','Justinian I',482,565,'Eastern Roman Empire','Eastern Roman emperor associated with legal codification and Mediterranean reconquests.',['ruler','byzantium','law'],['eastern-roman'],9),
H('muhammad','Muhammad',570,632,'Arabia','Founder of Islam and leader of the early Muslim community.',['religion','leader'],[],10),
H('charlemagne','Charlemagne',747,814,'Western Europe','Frankish ruler crowned emperor in 800 and presided over a large western European realm.',['ruler','franks','empire'],['carolingian'],10),
H('william-conqueror','William the Conqueror',1028,1087,'Normandy and England','Norman duke who conquered England in 1066 and became its king.',['ruler','conquest'],['england-kingdom'],10),
H('saladin','Saladin',1137,1193,'Middle East','Sultan who united major Muslim territories and defeated Crusader forces at Hattin.',['ruler','commander'],['ayyubid-sultanate'],9),
H('genghis-khan','Genghis Khan',1162,1227,'Mongolia','Founder of the Mongol Empire and organizer of a major Eurasian conquest state.',['ruler','conqueror'],['mongol'],10),
H('kublai-khan','Kublai Khan',1215,1294,'East Asia','Mongol ruler who founded the Yuan dynasty in China.',['ruler','china','mongol'],['yuan'],9),
H('ibn-battuta','Ibn Battuta',1304,1368,'North Africa and Eurasia','Moroccan traveler whose journeys provide important descriptions of fourteenth-century societies.',['traveler','scholar'],[],8),
H('timur','Timur',1336,1405,'Central Asia','Central Asian conqueror who founded the Timurid dynasty.',['ruler','conqueror'],['timurid'],9),
H('joan-arc','Joan of Arc',1412,1431,'France','French military and religious figure associated with the Lancastrian phase of the Hundred Years’ War.',['war','france'],[],8),
H('mehmed-conqueror','Mehmed II',1432,1481,'Ottoman Empire','Ottoman sultan who conquered Constantinople in 1453.',['ruler','ottoman','conquest'],['ottoman'],10),
H('isabella-castile','Isabella I of Castile',1451,1504,'Iberia','Queen of Castile whose reign coincided with the completion of the Reconquista and Columbus voyage.',['ruler','iberia'],['castile'],9),
H('columbus-person','Christopher Columbus',1451,1506,'Atlantic','Navigator whose 1492 voyage under Castilian sponsorship reached the Caribbean.',['explorer','atlantic'],['castile'],9),
H('leonardo','Leonardo da Vinci',1452,1519,'Italy','Italian artist, engineer and polymath of the Renaissance.',['artist','science','renaissance'],[],8),
H('martin-luther','Martin Luther',1483,1546,'Central Europe','German theologian whose writings helped initiate the Protestant Reformation.',['religion','reformation'],[],10),
H('suleiman','Suleiman the Magnificent',1494,1566,'Ottoman Empire','Ottoman sultan during a period of major imperial expansion and legal reform.',['ruler','ottoman'],['ottoman'],9),
H('galileo','Galileo Galilei',1564,1642,'Italy','Astronomer and physicist central to the Scientific Revolution.',['science','astronomy'],[],9),
H('shakespeare','William Shakespeare',1564,1616,'England','English playwright and poet whose works became central to the English literary canon.',['literature','culture'],[],9),
H('tokugawa-ieyasu','Tokugawa Ieyasu',1543,1616,'Japan','Japanese daimyo who established the Tokugawa shogunate.',['ruler','japan'],['tokugawa'],10),
H('gutenberg','Johannes Gutenberg',1400,1468,'Holy Roman Empire','European printer traditionally associated with the spread of movable-type printing in Europe.',['technology','printing'],[],9),
H('peter-great','Peter the Great',1672,1725,'Russia','Russian ruler who transformed institutions and expanded the Russian state.',['ruler','modernization'],['russian-tsardom','russian-empire'],9),
H('catherine-great','Catherine the Great',1729,1796,'Russia','Empress of Russia during territorial expansion and administrative reform.',['ruler','russia'],['russian-empire'],9),
H('george-washington','George Washington',1732,1799,'North America','Military commander of the American Revolution and first U.S. president.',['commander','president'],[],10),
H('jefferson','Thomas Jefferson',1743,1826,'North America','American statesman and principal drafter of the Declaration of Independence.',['statesman','revolution'],[],9),
H('napoleon','Napoleon Bonaparte',1769,1821,'France','French military and political leader who became emperor and reshaped Europe through war and administration.',['ruler','commander','france'],['first-empire'],10),
H('simón-bolivar','Simón Bolívar',1783,1830,'South America','Military and political leader associated with independence movements in northern South America.',['independence','commander'],['gran-colombia'],10),
H('abraham-lincoln','Abraham Lincoln',1809,1865,'United States','U.S. president during the Civil War who issued the Emancipation Proclamation.',['president','civil-war'],[],10),
H('queen-victoria','Queen Victoria',1819,1901,'Britain','British monarch whose reign coincided with industrialization and imperial expansion.',['monarch','britain'],['united-kingdom'],9),
H('otto-von-bismarck','Otto von Bismarck',1815,1898,'Germany','Prussian statesman who drove German unification and served as first imperial chancellor.',['statesman','unification'],['prussia','german-empire'],10),
H('florence-nightingale','Florence Nightingale',1820,1910,'Britain','Nursing reformer associated with changes in military and civilian medical care.',['medicine','reform'],[],8),
H('mahatma-gandhi','Mahatma Gandhi',1869,1948,'South Asia','Indian independence leader associated with mass nonviolent political action.',['independence','politics'],[],10),
H('mustafa-kemal','Mustafa Kemal Atatürk',1881,1938,'Turkey','Founder of the Republic of Turkey and leader of major state reforms after the Ottoman collapse.',['ruler','reform'],[],10),
H('woodrow-wilson','Woodrow Wilson',1856,1924,'United States','U.S. president during World War I and advocate of the League of Nations.',['president','diplomacy'],[],8),
H('vladimir-lenin','Vladimir Lenin',1870,1924,'Russia','Bolshevik revolutionary and head of the Soviet government after 1917.',['revolution','russia'],['russian-sfsr'],10),
H('joseph-stalin','Joseph Stalin',1878,1953,'Soviet Union','Soviet leader during forced industrialization, collectivization and World War II.',['ruler','soviet'],['soviet-union'],10),
H('winston-churchill','Winston Churchill',1874,1965,'Britain','British prime minister during much of World War II and a major wartime statesman.',['statesman','wwii'],['united-kingdom'],10),
H('franklin-roosevelt','Franklin D. Roosevelt',1882,1945,'United States','U.S. president during the Great Depression and most of World War II.',['president','economy','wwii'],[],10),
H('charles-de-gaulle','Charles de Gaulle',1890,1970,'France','French general and leader of Free France during World War II, later president of France.',['commander','statesman','wwii'],['free-france'],10),
H('hideki-tojo','Hideki Tojo',1884,1948,'Japan','Japanese general and prime minister during much of the Pacific War.',['ruler','wwii'],['meiji-japan'],8),
H('harry-truman','Harry S. Truman',1884,1972,'United States','U.S. president at the end of World War II and during the early Cold War.',['president','wwii','cold-war'],[],9),
H('jawaharlal-nehru','Jawaharlal Nehru',1889,1964,'South Asia','First prime minister of independent India and a prominent non-aligned statesman.',['statesman','india'],[],9),
H('mao-zedong','Mao Zedong',1893,1976,'China','Chinese Communist leader and founding leader of the People’s Republic of China.',['ruler','china','revolution'],[],10),
H('nelson-mandela','Nelson Mandela',1918,2013,'South Africa','Anti-apartheid leader and first president of South Africa elected after the end of apartheid.',['statesman','south-africa'],[],10),
H('martin-luther-king','Martin Luther King Jr.',1929,1968,'United States','Civil-rights leader associated with nonviolent activism in the United States.',['civil-rights','activism'],[],9),
H('john-kennedy','John F. Kennedy',1917,1963,'United States','U.S. president during a major phase of the Cold War, including the Cuban Missile Crisis.',['president','cold-war'],[],9),
H('nikita-khrushchev','Nikita Khrushchev',1894,1971,'Soviet Union','Soviet leader during de-Stalinization and the Cuban Missile Crisis.',['ruler','cold-war'],['soviet-union'],9),
H('ronald-reagan','Ronald Reagan',1911,2004,'United States','U.S. president during the later Cold War.',['president','cold-war'],[],8),
H('mikhail-gorbachev','Mikhail Gorbachev',1931,2022,'Soviet Union','Soviet leader associated with perestroika, glasnost and the final years of the USSR.',['ruler','cold-war'],['soviet-union'],10),
H('deng-xiaoping','Deng Xiaoping',1904,1997,'China','Chinese leader associated with economic reforms beginning in the late 1970s.',['ruler','economy','china'],[],9),
H('lech-walesa','Lech Wałęsa',1943,undefined,'Poland','Polish labor leader and later president associated with the Solidarity movement.',['politics','cold-war'],[],8),
H('malala','Malala Yousafzai',1997,undefined,'Pakistan','Pakistani education activist and Nobel Peace Prize laureate.',['activism','education'],[],7)
];

export const historicalEvents=historicalRecords.filter(r=>r.kind==='event');
export const historicalPlaces=historicalRecords.filter(r=>r.kind==='place');
export const historicalPeople=historicalRecords.filter(r=>r.kind==='person');
export function searchHistoricalRecords(query:string,kind?:HistoricalRecordKind){
 const q=query.trim().toLowerCase(); if(!q)return historicalRecords.filter(r=>!kind||r.kind===kind);
 return historicalRecords.filter(r=>(!kind||r.kind===kind)&&[r.name,r.region,r.description,...r.tags,...(r.relatedPolities??[])].join(' ').toLowerCase().includes(q));
}
export function recordsForYear(year:number){return historicalRecords.filter(r=>{const s=r.start??year;const e=r.end??s;return s<=year&&e>=year;});}
export function recordsNear(lat:number,lon:number,maxKm=250){return historicalPlaces.map(p=>({p,km:distanceKm(lat,lon,p.location!.lat,p.location!.lon)})).filter(x=>x.km<=maxKm).sort((a,b)=>a.km-b.km).map(x=>x.p);}
function distanceKm(a:number,b:number,c:number,d:number){const R=6371,rad=Math.PI/180;const x=(c-a)*rad,y=(d-b)*rad;const h=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
