export type PolityEra='ancient'|'medieval'|'early-modern'|'modern'|'unrecognized'|'subnational';
export type HistoricalPolity={
 id:string; name:string; era:PolityEra; start?:number; end?:number; region:string; aliases?:string[]; notes?:string;
};
/**
 * Historical-polity registry.
 * This is deliberately separate from the simulation state: a polity can exist in the
 * encyclopedia even when it is not selectable or active in a scenario.
 *
 * The registry is extensible and uses stable IDs so later era packs can add every
 * attested polity without changing save-game IDs.
 */
const rows:Array<[string,string,PolityEra,number,number,string,string[]]>=[
['akkad','Akkadian Empire','ancient',-2334,-2154,'Mesopotamia',[]],['sumer','Sumer','ancient',-4500,-1900,'Mesopotamia',[]],['ur-third-dynasty','Third Dynasty of Ur','ancient',-2112,-2004,'Mesopotamia',[]],
['old-babylonian','Old Babylonian Empire','ancient',-1894,-1595,'Mesopotamia',[]],['assyrian-empire','Assyrian Empire','ancient',-2500,-609,'Mesopotamia',[]],['neo-babylonian','Neo-Babylonian Empire','ancient',-626,-539,'Mesopotamia',[]],
['achaemenid','Achaemenid Empire','ancient',-550,-330,'Persia',[]],['seleucid','Seleucid Empire','ancient',-312,-63,'Middle East',[]],['parthian','Parthian Empire','ancient',-247,224,'Persia',[]],['sasanian','Sasanian Empire','ancient',224,651,'Persia',[]],
['ptolemaic','Ptolemaic Kingdom','ancient',-305,-30,'Egypt',[]],['macedon','Kingdom of Macedon','ancient',-808,-168,'Balkans',[]],['roman-republic','Roman Republic','ancient',-509,-27,'Mediterranean',[]],['roman-empire','Roman Empire','ancient',-27,395,'Mediterranean',[]],['western-roman','Western Roman Empire','ancient',395,476,'Europe',[]],['eastern-roman','Eastern Roman Empire','medieval',395,1453,'Eastern Mediterranean',['Byzantine Empire']],['gaul','Gaul','ancient',-50,486,'Western Europe',[]],['carthage','Carthaginian Empire','ancient',-814,-146,'North Africa',[]],['kingdom-of-kush','Kingdom of Kush','ancient',-1070,350,'Nile Valley',[]],
['aksum','Kingdom of Aksum','ancient',100,940,'Horn of Africa',[]],['ghaznavid','Ghaznavid Empire','medieval',977,1186,'Central Asia',[]],['seljuk','Great Seljuk Empire','medieval',1037,1194,'Middle East',[]],['khwarazmian','Khwarazmian Empire','medieval',1077,1231,'Central Asia',[]],['il-khanate','Ilkhanate','medieval',1256,1335,'Persia',[]],['timurid','Timurid Empire','medieval',1370,1507,'Central Asia',[]],
['mongol','Mongol Empire','medieval',1206,1368,'Eurasia',[]],['golden-horde','Golden Horde','medieval',1242,1502,'Eastern Europe',[]],['chagatai','Chagatai Khanate','medieval',1225,1347,'Central Asia',[]],['kiev-rus','Kievan Rus','medieval',882,1240,'Eastern Europe',[]],['novgorod','Novgorod Republic','medieval',1136,1478,'Eastern Europe',[]],['grand-principality-moscow','Grand Duchy of Moscow','medieval',1283,1547,'Eastern Europe',[]],
['holy-roman-empire','Holy Roman Empire','medieval',962,1806,'Central Europe',[]],['france-kingdom','Kingdom of France','medieval',987,1792,'Western Europe',[]],['england-kingdom','Kingdom of England','medieval',927,1707,'British Isles',[]],['scotland-kingdom','Kingdom of Scotland','medieval',843,1707,'British Isles',[]],
['castile','Crown of Castile','medieval',1065,1715,'Iberia',[]],['aragon','Crown of Aragon','medieval',1164,1716,'Iberia',[]],['portugal-kingdom','Kingdom of Portugal','medieval',1139,1910,'Iberia',[]],
['ottoman','Ottoman Empire','early-modern',1299,1922,'Anatolia',[]],['safavid','Safavid Iran','early-modern',1501,1736,'Persia',[]],['mughal','Mughal Empire','early-modern',1526,1857,'South Asia',[]],['maratha','Maratha Confederacy','early-modern',1674,1818,'South Asia',[]],
['qing','Qing Empire','early-modern',1636,1912,'East Asia',[]],['ming','Ming dynasty','early-modern',1368,1644,'East Asia',[]],['yuan','Yuan dynasty','medieval',1271,1368,'East Asia',[]],['lialiao','Liao dynasty','medieval',916,1125,'East Asia',[]],['jurchen-jin','Jin dynasty','medieval',1115,1234,'East Asia',[]],
['joseon','Joseon','early-modern',1392,1897,'Korea',[]],['korean-empire','Korean Empire','modern',1897,1910,'Korea',[]],['tokugawa','Tokugawa shogunate','early-modern',1603,1868,'Japan',[]],['meiji-japan','Empire of Japan','modern',1868,1947,'Japan',[]],
['aztec','Aztec Empire','early-modern',1428,1521,'Mesoamerica',[]],['inca','Inca Empire','early-modern',1438,1533,'Andes',[]],['maya','Maya civilization','ancient',-2000,1697,'Mesoamerica',[]],['toltec','Toltec civilization','ancient',900,1150,'Mesoamerica',[]],
['mali','Mali Empire','medieval',1235,1645,'West Africa',[]],['songhai','Songhai Empire','medieval',1464,1591,'West Africa',[]],['ghana-empire','Ghana Empire','medieval',300,1200,'West Africa',[]],['kanem-bornu','Kanem-Bornu Empire','medieval',700,1893,'Central Africa',[]],['ethiopian-empire','Ethiopian Empire','medieval',1270,1974,'Horn of Africa',[]],
['benin-kingdom','Kingdom of Benin','medieval',1180,1897,'West Africa',[]],['ashanti','Ashanti Empire','early-modern',1701,1957,'West Africa',[]],['kongo','Kingdom of Kongo','early-modern',1390,1914,'Central Africa',[]],
['great-zimbabwe','Kingdom of Zimbabwe','medieval',1100,1450,'Southern Africa',[]],['mutapa','Kingdom of Mutapa','early-modern',1430,1760,'Southern Africa',[]],
['swahili-city-states','Swahili city-states','medieval',700,1700,'East Africa',[]],['kilwa','Kilwa Sultanate','medieval',957,1513,'East Africa',[]],
['khmer-empire','Khmer Empire','medieval',802,1431,'Southeast Asia',[]],['srivijaya','Srivijaya','medieval',650,1377,'Southeast Asia',[]],['majapahit','Majapahit Empire','medieval',1293,1527,'Southeast Asia',[]],['pagan-kingdom','Pagan Kingdom','medieval',849,1297,'Southeast Asia',[]],['ayutthaya','Ayutthaya Kingdom','early-modern',1351,1767,'Southeast Asia',[]],['dai-viet','Đại Việt','medieval',1054,1804,'Vietnam',[]],
['polish-lithuanian','Polish-Lithuanian Commonwealth','early-modern',1569,1795,'Eastern Europe',[]],['poland-second','Second Polish Republic','modern',1918,1939,'Eastern Europe',[]],['austro-hungarian','Austria-Hungary','modern',1867,1918,'Central Europe',[]],['austrian-empire','Austrian Empire','early-modern',1804,1867,'Central Europe',[]],['prussia','Kingdom of Prussia','early-modern',1701,1918,'Central Europe',[]],
['german-empire','German Empire','modern',1871,1918,'Central Europe',[]],['weimar','Weimar Republic','modern',1919,1933,'Central Europe',[]],['francois-first-empire','First French Empire','early-modern',1804,1815,'Western Europe',[]],['napoleonic-kingdom-italy','Napoleonic Kingdom of Italy','early-modern',1805,1814,'Italy',[]],
['spanish-empire','Spanish Empire','early-modern',1492,1976,'Iberia and Americas',[]],['portuguese-empire','Portuguese Empire','early-modern',1415,1999,'Global',[]],['dutch-empire','Dutch Empire','early-modern',1581,1975,'Global',[]],['british-empire','British Empire','early-modern',1583,1997,'Global',[]],['french-colonial-empire','French colonial empire','early-modern',1534,1980,'Global',[]],
['belgian-colonial-empire','Belgian colonial empire','modern',1885,1962,'Central Africa',[]],['italian-empire','Italian Empire','modern',1885,1943,'Africa',[]],['german-colonial-empire','German colonial empire','modern',1884,1919,'Global',[]],
['russian-empire','Russian Empire','early-modern',1721,1917,'Eurasia',[]],['soviet-union','Soviet Union','modern',1922,1991,'Eurasia',['USSR']],['russian-sfsr','Russian SFSR','modern',1917,1991,'Eurasia',[]],['yugoslavia-kingdom','Kingdom of Yugoslavia','modern',1918,1941,'Balkans',[]],['yugoslavia-socialist','Socialist Federal Republic of Yugoslavia','modern',1945,1992,'Balkans',[]],
['czechoslovakia-first','First Czechoslovak Republic','modern',1918,1938,'Central Europe',[]],['czechoslovakia-second','Second Czechoslovak Republic','modern',1938,1939,'Central Europe',[]],['czechoslovakia-socialist','Czechoslovak Socialist Republic','modern',1960,1990,'Central Europe',[]],
['ottoman-beylik','Ottoman Beylik','medieval',1299,1453,'Anatolia',[]],['kingdom-of-greece','Kingdom of Greece','modern',1832,1924,'Balkans',[]],['greek-republic','Second Hellenic Republic','modern',1924,1935,'Balkans',[]],
['mexican-empire','First Mexican Empire','modern',1821,1823,'Mesoamerica',[]],['second-mexican-empire','Second Mexican Empire','modern',1864,1867,'Mesoamerica',[]],['gran-colombia','Gran Colombia','modern',1819,1831,'South America',[]],['viceroyalty-new-spain','Viceroyalty of New Spain','early-modern',1535,1821,'Americas',[]],['viceroyalty-peru','Viceroyalty of Peru','early-modern',1542,1824,'South America',[]],['viceroyalty-rio-plata','Viceroyalty of the Río de la Plata','early-modern',1776,1814,'South America',[]],
['united-provinces-rio','United Provinces of the Río de la Plata','modern',1810,1831,'South America',[]],['empire-brazil','Empire of Brazil','modern',1822,1889,'South America',[]],['kingdom-hawaii','Kingdom of Hawaii','modern',1795,1893,'Pacific',[]],['australian-commonwealth','Commonwealth of Australia','modern',1901,9999,'Oceania',[]],
['manchu-state','Manchukuo','modern',1932,1945,'East Asia',[]],['republic-china','Republic of China','modern',1912,9999,'East Asia',[]],['korean-peoples-republic','Provisional People’s Committee of North Korea','modern',1946,1948,'Korea',[]],
['free-france','Free France','modern',1940,1944,'Europe',[]],['vichy-france','French State','modern',1940,1944,'Western Europe',['Vichy France']],['italian-social-republic','Italian Social Republic','modern',1943,1945,'Italy',['Salò Republic']],
['ukrainian-people-republic','Ukrainian People’s Republic','modern',1917,1921,'Eastern Europe',[]],['west-ukrainian','West Ukrainian People’s Republic','modern',1918,1919,'Eastern Europe',[]],['belarusian-democratic-republic','Belarusian Democratic Republic','modern',1918,1919,'Eastern Europe',[]],['georgian-democratic-republic','Democratic Republic of Georgia','modern',1918,1921,'Caucasus',[]],['armenia-first-republic','First Republic of Armenia','modern',1918,1920,'Caucasus',[]],['azerbaijan-democratic-republic','Azerbaijan Democratic Republic','modern',1918,1920,'Caucasus',[]],
['tannu-tuva','Tuvan People’s Republic','modern',1921,1944,'Central Asia',[]],['mongolian-peoples-republic','Mongolian People’s Republic','modern',1924,1992,'East Asia',[]],['east-turkestan-republic','East Turkestan Republic','modern',1933,1934,'Central Asia',[]],['second-east-turkestan','Second East Turkestan Republic','modern',1944,1949,'Central Asia',[]],
['arab-republic-egypt-syria','United Arab Republic','modern',1958,1971,'Middle East',[]],['united-arab-states','United Arab States','modern',1958,1961,'Middle East',[]],['united-arab-republic','United Arab Republic','modern',1958,1971,'Middle East',[]],
['rhodesia','Rhodesia','modern',1965,1979,'Southern Africa',['Rhodesian Front']],['katanga','State of Katanga','modern',1960,1963,'Central Africa',[]],['biafra','Republic of Biafra','modern',1967,1970,'West Africa',[]],['somaliland-1991','Republic of Somaliland','modern',1991,9999,'Horn of Africa',[]],
['transkei','Transkei','modern',1976,1994,'Southern Africa',[]],['bophuthatswana','Bophuthatswana','modern',1977,1994,'Southern Africa',[]],['venda','Venda','modern',1979,1994,'Southern Africa',[]],['ciskei','Ciskei','modern',1981,1994,'Southern Africa',[]]
];
export const historicalPolities:Record<string,HistoricalPolity>=Object.fromEntries(rows.map(([id,name,era,start,end,region,aliases])=>[id,{id,name,era,start,end,region,aliases}]));
export function searchHistoricalPolities(query:string){const q=query.toLowerCase().trim();return Object.values(historicalPolities).filter(p=>p.name.toLowerCase().includes(q)||(p.aliases??[]).some(a=>a.toLowerCase().includes(q)));}
export function politiesAtYear(year:number){return Object.values(historicalPolities).filter(p=>(p.start??-99999)<=year&&(p.end??99999)>=year);}
